apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: payu-keycloak-admin
spec:
  vaultAuthRef: payu-vault
  mount: secret
  type: kv-v2
  path: payu/dev/keycloak/credentials
  refreshAfter: 1h
  hmacSecretData: true
  destination:
    name: payu-keycloak-admin
    create: true
    overwrite: true
    labels:
      app.kubernetes.io/component: secrets
      app.kubernetes.io/name: payu-keycloak-admin
      app.kubernetes.io/part-of: payu
    transformation:
      excludes:
        - .*
      templates:
        username:
          text: '{{ get .Secrets "KEYCLOAK_ADMIN_USERNAME" }}'
        password:
          text: '{{ get .Secrets "KEYCLOAK_ADMIN_PASSWORD" }}'
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: payu-keycloak-db
spec:
  vaultAuthRef: payu-vault
  mount: secret
  type: kv-v2
  path: payu/dev/keycloak/database
  refreshAfter: 1h
  hmacSecretData: true
  destination:
    name: payu-keycloak-db
    create: true
    overwrite: true
    labels:
      app.kubernetes.io/component: secrets
      app.kubernetes.io/name: payu-keycloak-db
      app.kubernetes.io/part-of: payu
    transformation:
      excludes:
        - .*
      templates:
        username:
          text: '{{ get .Secrets "POSTGRES_USERNAME" }}'
        password:
          text: '{{ get .Secrets "POSTGRES_PASSWORD" }}'
