apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: payu-keycloak-admin
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: payu-vault
    kind: ClusterSecretStore
  target:
    name: payu-keycloak-admin
    creationPolicy: Owner
    template:
      metadata:
        labels:
          app.kubernetes.io/component: secrets
          app.kubernetes.io/name: payu-keycloak-admin
          app.kubernetes.io/part-of: payu
  data:
    - secretKey: username
      remoteRef:
        key: payu/keycloak-credentials
        property: KEYCLOAK_ADMIN_USERNAME
    - secretKey: password
      remoteRef:
        key: payu/keycloak-credentials
        property: KEYCLOAK_ADMIN_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: payu-keycloak-db
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: payu-vault
    kind: ClusterSecretStore
  target:
    name: payu-keycloak-db
    creationPolicy: Owner
    template:
      metadata:
        labels:
          app.kubernetes.io/component: secrets
          app.kubernetes.io/name: payu-keycloak-db
          app.kubernetes.io/part-of: payu
  data:
    - secretKey: username
      remoteRef:
        key: payu/keycloak-db
        property: POSTGRES_USERNAME
    - secretKey: password
      remoteRef:
        key: payu/keycloak-db
        property: POSTGRES_PASSWORD