apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  labels:
    app.kubernetes.io/part-of: payu
type: Opaque
stringData:
  ANALYTICS_DATABASE_URL: "postgresql+asyncpg://payu:payu-dev-password@payu-postgres-primary.payu-dev.svc.cluster.local:5432/payu_analytics"
  KYC_DATABASE_URL: "postgresql+asyncpg://payu:payu-dev-password@payu-postgres-primary.payu-dev.svc.cluster.local:5432/payu_kyc"
  DB_USERNAME: "payu"
  DB_PASSWORD: "payu-dev-password"

