apiVersion: v1
kind: Secret
metadata:
  name: dev-env-secrets
  labels:
    app.kubernetes.io/part-of: payu
type: Opaque
stringData:
  ENCRYPTION_SALT: "PayU-DEV-PBKDF2-Salt-v3-2026-!SafeForDevOnly!"
  WEBHOOK_SECRET: "payu-dev-webhook-secret-2026-not-default-value"
  JWT_SECRET: "PayU-DEV-JWT-Secret-Key-2026-VerySecure32BytesLengthKey!"
  secret-key: "PayU-DEV-SecretKey-2026-!SafeForDevOnly!"
  encryption-key: "PayU-DEV-PBKDF2-Salt-v3-2026-!SafeForDevOnly!"
  BLIND_INDEX_KEY: "PayU-DEV-BlindIndexKey-2026-32BytesLongSecret!"
