apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: payu-dev
resources:
  - ../../../base/biller-simulator
images:
  - name: image-registry.openshift-image-registry.svc:5000/payu-dev/biller-simulator
    newName: image-registry.openshift-image-registry.svc:5000/payu-dev/biller-simulator
    newTag: "1.18.59"
patches:
  - target:
      kind: Deployment
      name: biller-simulator
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: biller-simulator
      spec:
        template:
          spec:
            containers:
              - name: app
                env:
                  - name: OIDC_ISSUER
                    value: "https://sso-dev.apps.fajjjar.my.id/realms/payu"
