apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  name: payu-ghxd9-worker-ap-southeast-1b
  namespace: openshift-machine-api
  labels:
    machine.openshift.io/cluster-api-cluster: payu-ghxd9
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: payu-ghxd9
      machine.openshift.io/cluster-api-machineset: payu-ghxd9-worker-ap-southeast-1b
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: payu-ghxd9
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: payu-ghxd9-worker-ap-southeast-1b
    spec:
      providerSpec:
        value:
          ami:
            id: ami-0aca5cb2df4f2bb2a
          apiVersion: machine.openshift.io/v1beta1
          blockDevices:
            - ebs:
                encrypted: true
                iops: 0
                kmsKey:
                  arn: ""
                volumeSize: 100
                volumeType: gp3
          credentialsSecret:
            name: aws-cloud-credentials
          deviceIndex: 0
          iamInstanceProfile:
            id: payu-ghxd9-worker-profile
          instanceType: m6a.4xlarge
          kind: AWSMachineProviderConfig
          metadataServiceOptions:
            authentication: Required
          placement:
            availabilityZone: ap-southeast-1b
            region: ap-southeast-1
          securityGroups:
            - filters:
                - name: tag:Name
                  values: [payu-ghxd9-node]
            - filters:
                - name: tag:Name
                  values: [payu-ghxd9-lb]
          subnet:
            id: subnet-062350c174d9b0c59
          tags:
            - name: kubernetes.io/cluster/payu-ghxd9
              value: owned
          userDataSecret:
            name: worker-user-data
---
apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  name: payu-ghxd9-worker-ap-southeast-1c
  namespace: openshift-machine-api
  labels:
    machine.openshift.io/cluster-api-cluster: payu-ghxd9
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: payu-ghxd9
      machine.openshift.io/cluster-api-machineset: payu-ghxd9-worker-ap-southeast-1c
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: payu-ghxd9
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: payu-ghxd9-worker-ap-southeast-1c
    spec:
      providerSpec:
        value:
          ami:
            id: ami-0aca5cb2df4f2bb2a
          apiVersion: machine.openshift.io/v1beta1
          blockDevices:
            - ebs:
                encrypted: true
                iops: 0
                kmsKey:
                  arn: ""
                volumeSize: 100
                volumeType: gp3
          credentialsSecret:
            name: aws-cloud-credentials
          deviceIndex: 0
          iamInstanceProfile:
            id: payu-ghxd9-worker-profile
          instanceType: m6a.4xlarge
          kind: AWSMachineProviderConfig
          metadataServiceOptions:
            authentication: Required
          placement:
            availabilityZone: ap-southeast-1c
            region: ap-southeast-1
          securityGroups:
            - filters:
                - name: tag:Name
                  values: [payu-ghxd9-node]
            - filters:
                - name: tag:Name
                  values: [payu-ghxd9-lb]
          subnet:
            id: subnet-0da646869198d1549
          tags:
            - name: kubernetes.io/cluster/payu-ghxd9
              value: owned
          userDataSecret:
            name: worker-user-data
