apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: payu-preprod
resources:
  - ../../../base/qris-simulator.yaml
images:
  - name: image-registry.openshift-image-registry.svc:5000/payu-dev/qris-simulator
    newName: image-registry.openshift-image-registry.svc:5000/payu-preprod/qris-simulator
    newTag: "1.18.40"
