package id.payu.api.common.exception.problem;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.servlet.http.HttpServletRequest;
import lombok.Builder;
import lombok.Data;
import org.springframework.http.HttpStatus;

import java.net.URI;
import java.util.UUID;

/**
 * RFC 9457 (formerly RFC 7807) Problem Details for HTTP APIs.
 *
 * <p>PayU extensions over the IETF base spec:
 * <ul>
 *   <li>{@code error_code} — PayU-specific error code (e.g. {@code TXN_400}, {@code ACC_001})</li>
 *   <li>{@code trace_id} — correlation/trace id for distributed tracing</li>
 *   <li>{@code timestamp} — server-side timestamp in ISO 8601</li>
 * </ul>
 *
 * <p>Media type: {@code application/problem+json} (per RFC 9457 §3).
 *
 * <p>Field order is fixed for client compatibility (type, title, status, detail, instance,
 * error_code, trace_id, timestamp, errors).
 *
 * @see <a href="https://www.rfc-editor.org/rfc/rfc9457.html">RFC 9457</a>
 */
@Data
@Builder
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({"type", "title", "status", "detail", "instance", "error_code", "trace_id", "timestamp", "errors"})
@Schema(description = "RFC 9457 Problem Details response")
public class ProblemDetail {

    @Schema(description = "URI reference identifying the problem type",
            example = "https://payu.id/problems/validation-error")
    private URI type;

    @Schema(description = "Short human-readable summary of the problem type",
            example = "Validation failed")
    private String title;

    @Schema(description = "HTTP status code generated by the origin server",
            example = "400")
    private Integer status;

    @Schema(description = "Human-readable explanation specific to this occurrence",
            example = "Field 'amount' must be positive")
    private String detail;

    @Schema(description = "URI identifying the specific occurrence of the problem",
            example = "/api/v1/transfers")
    private String instance;

    @JsonProperty("error_code")
    @Schema(description = "PayU-specific error code (machine-readable)",
            example = "TXN_400")
    private String errorCode;

    @JsonProperty("trace_id")
    @Schema(description = "Distributed trace/correlation id for the request",
            example = "550e8400-e29b-41d4-a716-446655440000")
    private String traceId;

    @Schema(description = "Server-side timestamp in ISO 8601")
    private String timestamp;

    @Schema(description = "Per-field validation errors (RFC 9457 §3.1 extension members)")
    private java.util.List<FieldViolation> errors;

    /**
     * Builds a ProblemDetail from a Spring exception handler context.
     *
     * @param status    HTTP status code
     * @param title     human-readable title
     * @param detail    human-readable detail
     * @param errorCode PayU error code
     * @param request   the servlet request (for instance URI + trace_id)
     * @return fully-populated ProblemDetail
     */
    public static ProblemDetail of(HttpStatus status, String title, String detail, String errorCode,
                                   HttpServletRequest request) {
        return ProblemDetail.builder()
                .type(defaultTypeFor(status))
                .title(title)
                .status(status.value())
                .detail(detail)
                .instance(request != null ? request.getRequestURI() : null)
                .errorCode(errorCode)
                .traceId(extractTraceId(request))
                .timestamp(java.time.Instant.now().toString())
                .build();
    }

    /**
     * Builds a ProblemDetail with field-level validation errors.
     */
    public static ProblemDetail of(HttpStatus status, String title, String detail, String errorCode,
                                   HttpServletRequest request, java.util.List<FieldViolation> errors) {
        ProblemDetail pd = of(status, title, detail, errorCode, request);
        pd.setErrors(errors);
        return pd;
    }

    private static URI defaultTypeFor(HttpStatus status) {
        // Per RFC 9457 §4.2, "about:blank" is the default if no type is provided.
        // We use a PayU-namespaced URI for non-generic problems.
        if (status == null) {
            return URI.create("about:blank");
        }
        return switch (status) {
            case BAD_REQUEST -> URI.create("https://payu.id/problems/bad-request");
            case UNAUTHORIZED -> URI.create("https://payu.id/problems/unauthorized");
            case FORBIDDEN -> URI.create("https://payu.id/problems/forbidden");
            case NOT_FOUND -> URI.create("https://payu.id/problems/not-found");
            case CONFLICT -> URI.create("https://payu.id/problems/conflict");
            case UNPROCESSABLE_ENTITY -> URI.create("https://payu.id/problems/unprocessable-entity");
            case TOO_MANY_REQUESTS -> URI.create("https://payu.id/problems/too-many-requests");
            case BAD_GATEWAY -> URI.create("https://payu.id/problems/bad-gateway");
            case SERVICE_UNAVAILABLE -> URI.create("https://payu.id/problems/service-unavailable");
            default -> URI.create("about:blank");
        };
    }

    private static String extractTraceId(HttpServletRequest request) {
        if (request == null) {
            return UUID.randomUUID().toString();
        }
        String traceId = request.getHeader("X-Trace-Id");
        if (traceId == null || traceId.isBlank()) {
            traceId = request.getHeader("X-Correlation-ID");
        }
        if (traceId == null || traceId.isBlank()) {
            traceId = UUID.randomUUID().toString();
        }
        return traceId;
    }
}
