apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-server-certificate-staging
  namespace: openshift-config
spec:
  secretName: api-server-tls-secret-staging
  commonName: api.payu.ocp.fajjjar.my.id
  dnsNames:
    - api.payu.ocp.fajjjar.my.id
  privateKey:
    algorithm: RSA
    size: 2048
    rotationPolicy: Never
  duration: 720h # 30d
  renewBefore: 168h # 7d
  issuerRef:
    name: letsencrypt-staging-issuer
    kind: ClusterIssuer
    group: cert-manager.io
