apiVersion: rhpam.kiegroup.org/v1
kind: KogitoInfra
metadata:
  name: lending-rules-infra
  labels:
    app.kubernetes.io/name: lending-rules-infra
    app.kubernetes.io/part-of: payu
    app.kubernetes.io/component: rules-engine
spec:
  resource:
    apiVersion: kafka.strimzi.io/v1beta2
    kind: Kafka
    name: payu-kafka
