apiVersion: rhpam.kiegroup.org/v1
kind: KogitoRuntime
metadata:
  name: lending-rules
  labels:
    app.kubernetes.io/name: lending-rules
    app.kubernetes.io/part-of: payu
    app.kubernetes.io/component: rules-engine
    app.kubernetes.io/version: 1.8.2
    team: backend
spec:
  runtime: springboot
  replicas: 1
  image: image-registry.openshift-image-registry.svc:5000/payu-dev/lending-rules:1.8.83
  insecureImageRegistry: true

  env:
    - name: SPRING_PROFILES_ACTIVE
      value: container
    - name: SERVER_PORT
      value: '8080'

  probes:
    livenessProbe:
      httpGet:
        path: /actuator/health/liveness
        port: 8080
      initialDelaySeconds: 30
      periodSeconds: 15
    startupProbe:
      httpGet:
        path: /actuator/health/liveness
        port: 8080
      initialDelaySeconds: 10
      periodSeconds: 5
      failureThreshold: 30
