apiVersion: v1
kind: Service
metadata:
  name: lending-rules
  namespace: payu-dev
  labels:
    app.kubernetes.io/name: lending-rules
    app.kubernetes.io/part-of: payu
    app.kubernetes.io/version: 1.8.85
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: lending-rules
  ports:
  - port: 8080
    targetPort: 8080
    name: http
