apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: payu-uat
resources:
  - ../../../base/kyc-service
images:
  - name: image-registry.openshift-image-registry.svc:5000/payu-dev/kyc-service
    newName: image-registry.openshift-image-registry.svc:5000/payu-uat/kyc-service
    newTag: "1.18.26"
patches:
  - target:
      kind: Deployment
      name: kyc-service
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: SPRINGDOC_API_DOCS_ENABLED
          value: "true"
