apiVersion: v1
kind: Secret
metadata:
  name: noobaa-aws-cloud-credentials
  namespace: openshift-storage
type: Opaque
stringData:
  credentials: |
    [default]
    role_arn = arn:aws:iam::787842753050:role/payu-onprem-odf-noobaa
    web_identity_token_file = /var/run/secrets/openshift/serviceaccount/token
