apiVersion: v1
kind: ConfigMap
metadata:
  name: log-alert-rules
  namespace: openshift-logging
  labels:
    app: payu
    type: log-alerts
data:
  log-alerts.yaml: |
    groups:
      - name: payu_log_alerts
        interval: 30s
        rules:
          # Critical Error Rate Alert
          - alert: CriticalErrorRateSpike
            expr: |
              (
                sum(rate({namespace="payu-prod", level="ERROR"}[5m])) by (service)
                /
                sum(rate({namespace="payu-prod"}[5m])) by (service)
              ) > 0.05
            for: 5m
            labels:
              severity: critical
              team: platform
            annotations:
              summary: "Critical error rate spike in {{ $labels.service }}"
              description: "Error rate has exceeded 5% for service {{ $labels.service }}"
              runbook: "https://docs.payu.internal/runbooks/error-rate-spike"

          # Security Alert: Authentication Failures
          - alert: AuthenticationFailureSpike
            expr: |
              sum(rate({namespace="payu-prod", service="auth-service"} |~ ".*authentication failed.*"[5m])) > 100
            for: 2m
            labels:
              severity: warning
              team: security
            annotations:
              summary: "High rate of authentication failures"
              description: "More than 100 authentication failures per minute detected"
              runbook: "https://docs.payu.internal/runbooks/auth-failures"

          # Security Alert: Authorization Failures
          - alert: AuthorizationFailureSpike
            expr: |
              sum(rate({namespace="payu-prod"} |~ ".*access denied.*|.*unauthorized.*"[5m])) > 50
            for: 5m
            labels:
              severity: warning
              team: security
            annotations:
              summary: "High rate of authorization failures"
              description: "Possible security breach attempt detected"

          # Application Alert: Payment Failures
          - alert: PaymentFailureRateSpike
            expr: |
              (
                sum(rate({namespace="payu-prod", service="transaction-service"} |~ ".*payment failed.*"[5m]))
                /
                sum(rate({namespace="payu-prod", service="transaction-service"} |~ ".*payment.*"[5m]))
              ) > 0.1
            for: 5m
            labels:
              severity: critical
              team: backend
            annotations:
              summary: "High payment failure rate"
              description: "Payment failure rate exceeds 10%"

          # Infrastructure Alert: Database Connection Errors
          - alert: DatabaseConnectionErrors
            expr: |
              sum(rate({namespace="payu-prod"} |~ ".*connection refused.*|.*could not connect to database.*"[5m])) > 10
            for: 2m
            labels:
              severity: critical
              team: platform
            annotations:
              summary: "Database connection errors detected"
              description: "Multiple services are experiencing database connection issues"

          # Infrastructure Alert: OutOfMemory Errors
          - alert: OutOfMemoryErrors
            expr: |
              sum(rate({namespace="payu-prod"} |~ ".*OutOfMemoryError.*|.*OOM.*"[5m])) > 0
            for: 1m
            labels:
              severity: critical
              team: platform
            annotations:
              summary: "OutOfMemoryError detected"
              description: "A service has run out of memory and may have crashed"

          # Business Alert: Transaction Timeout
          - alert: TransactionTimeoutSpike
            expr: |
              sum(rate({namespace="payu-prod", service="transaction-service"} |~ ".*timeout.*"[5m])) > 10
            for: 5m
            labels:
              severity: warning
              team: backend
            annotations:
              summary: "High transaction timeout rate"
              description: "Transaction timeouts are occurring frequently"

          # Compliance Alert: PII Data Leakage
          - alert: PIDataLeakage
            expr: |
              sum(count_over_time({namespace="payu-prod"} |~ ".*NIK.*|.*KTP.*|.*[0-9]{16}.*"[5m])) > 0
            for: 1m
            labels:
              severity: critical
              team: security
            annotations:
              summary: "Potential PII data leakage in logs"
              description: "Personal identity information detected in application logs"

      - name: payu_log_quality
        interval: 1m
        rules:
          # Log Volume Alert
          - alert: ExcessiveLogVolume
            expr: |
              sum(rate({namespace="payu-prod"}[5m])) > 10000
            for: 10m
            labels:
              severity: warning
              team: platform
            annotations:
              summary: "Excessive log volume detected"
              description: "Log volume exceeds 10,000 entries per second"

          # Missing Trace IDs
          - alert: MissingTraceIds
            expr: |
              (
                sum(rate({namespace="payu-prod", trace_id="unknown"}[5m]))
                /
                sum(rate({namespace="payu-prod"}[5m]))
              ) > 0.5
            for: 5m
            labels:
              severity: warning
              team: platform
            annotations:
              summary: "High rate of logs without trace IDs"
              description: "More than 50% of logs are missing trace correlation IDs"

      - name: payu_anomaly_detection
        interval: 5m
        rules:
          # Unusual Log Pattern Detection
          - alert: UnusualLogPattern
            expr: |
              (
                sum(rate({namespace="payu-prod"}[5m]))
                -
                avg_over_time(sum(rate({namespace="payu-prod"}[5m]))[1h:5m])
              )
              /
              avg_over_time(sum(rate({namespace="payu-prod"}[5m]))[1h:5m])
              > 2
            for: 10m
            labels:
              severity: info
              team: platform
            annotations:
              summary: "Unusual log pattern detected"
              description: "Log volume has deviated significantly from the 1-hour average"
---
apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
  namespace: openshift-logging
  labels:
    app: payu
    type: log-export
stringData:
  AWS_ACCESS_KEY_ID: "your-access-key-id"
  AWS_SECRET_ACCESS_KEY: "your-secret-access-key"
  AWS_REGION: "ap-southeast-1"
  S3_BUCKET: "payu-logs-compliance"
type: Opaque
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: log-export-to-s3
  namespace: openshift-logging
  labels:
    app: payu
    type: log-export
spec:
  schedule: "0 */6 * * *" # Every 6 hours
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: log-exporter-sa
          containers:
          - name: log-exporter
            image: amazon/aws-cli:latest
            command:
            - /bin/bash
            - -c
            - |
              #!/bin/bash
              set -e

              TIMESTAMP=$(date +%Y-%m-%d-%H)
              LOG_FILE="/tmp/payu-logs-${TIMESTAMP}.json.gz"

              echo "Starting log export at $(date)"

              # Query Loki for critical logs in the last 6 hours
              QUERY='{level="ERROR"} |= "failed|timeout|exception|critical"'
              START=$(date -d '6 hours ago' +%s)
              END=$(date +%s)

              # Export logs from Loki
              curl -G "http://loki.openshift-logging.svc:3100/loki/api/v1/query_range" \
                --data-urlencode "query=${QUERY}" \
                --data-urlencode "start=${START}"000000000 \
                --data-urlencode "end=${END}"000000000 \
                --data-urlencode "limit=10000" \
                | jq -c '.data.result[].values[][1]' > /tmp/logs.json

              # Compress logs
              gzip -c /tmp/logs.json > $LOG_FILE

              # Upload to S3
              aws s3 cp $LOG_FILE \
                s3://payu-logs-compliance/critical/${TIMESTAMP}.json.gz \
                --storage-class GLACIER

              # Clean up local file
              rm -f /tmp/logs.json $LOG_FILE

              echo "Log export completed at $(date)"
            env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: AWS_REGION
            - name: AWS_DEFAULT_REGION
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: AWS_REGION
          restartPolicy: OnFailure
          backoffLimit: 3
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: log-exporter-sa
  namespace: openshift-logging
  labels:
    app: payu
    type: log-export
