apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../rhtas
patches:
  - target:
      kind: PersistentVolumeClaim
      name: rhtas-tuf
    patch: |-
      - op: replace
        path: /spec/storageClassName
        value: efs-csi
  - target:
      group: rhtas.redhat.com
      version: v1alpha1
      kind: Securesign
      name: securesign-ha
    patch: |-
      - op: replace
        path: /spec/tuf/pvc/storageClass
        value: efs-csi
  - target:
      kind: StatefulSet
      name: rhtas-redis
    patch: |-
      - op: replace
        path: /spec/template/spec/affinity/podAntiAffinity/requiredDuringSchedulingIgnoredDuringExecution/0/topologyKey
        value: kubernetes.io/hostname
  - target:
      group: postgresql.cnpg.io
      version: v1
      kind: Cluster
      name: rhtas-postgres
    patch: |-
      - op: replace
        path: /spec/instances
        value: 3
      - op: replace
        path: /spec/affinity/topologyKey
        value: kubernetes.io/hostname
