apiVersion: v1
kind: ConfigMap
metadata:
  name: rhacs-central-ca
  namespace: payu-cicd
  labels:
    app.kubernetes.io/name: rhacs-central-ca
    app.kubernetes.io/part-of: payu
    app.kubernetes.io/component: supply-chain-security
data:
  # Central service CA — refresh from the live cluster after any Central
  # reinstall: oc get secret central-tls -n stackrox -o jsonpath='{.data.ca\.pem}'
  ca.pem: |
    -----BEGIN CERTIFICATE-----
    MIIB0zCCAXqgAwIBAgIUB7urDkIUwMOF31yiVd1sgAbKg0wwCgYIKoZIzj0EAwIw
    SDEnMCUGA1UEAxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MR0wGwYD
    VQQFExQxMDk3Nzk5NjE1MTczMjIxMTI4NDAeFw0yNjA4MjIyMDI0MDBaFw0zMTA4
    MjEyMDI0MDBaMEgxJzAlBgNVBAMTHlN0YWNrUm94IENlcnRpZmljYXRlIEF1dGhv
    cml0eTEdMBsGA1UEBRMUMTA5Nzc5OTYxNTE3MzIyMTEyODQwWTATBgcqhkjOPQIB
    BggqhkjOPQMBBwNCAARZefGUqA/XYBYY6ur/YPZr66/WDRKpYVocEHtvA/l0pu+b
    EpkfyMsFyxqEYoeiUfOfOQRMaESakFS9EOXOyou6o0IwQDAOBgNVHQ8BAf8EBAMC
    AQYwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUVNlXyQbq3NPfKDG6U8MMxsQX
    2CgwCgYIKoZIzj0EAwIDRwAwRAIgRTodLHAoQ9ifJpf54ODQYeDu2uMi5uoKVrOT
    dZVCLEQCIHdmNwk1+/ErIGV2zqz1R2ATHvszoUeWbuXnJQejl00Y
    -----END CERTIFICATE-----
