apiVersion: v1
kind: Secret
metadata:
  name: signing-secrets
  namespace: payu-cicd
  labels:
    app.kubernetes.io/part-of: payu
    app.kubernetes.io/component: cicd
type: Opaque
stringData:
  cosign.key: |
    -----BEGIN ENCRYPTED SIGSTORE PRIVATE KEY-----
    eyJrZGYiOnsibmFtZSI6InNjcnlwdCIsInBhcmFtcyI6eyJOIjo2NTUzNiwiciI6
    OCwicCI6MX0sInNhbHQiOiJkQUpZYkJLYjBQUjJ1aHBuOGtYbUtyQm91Y2JRanpE
    dWdqTXVTWklsUEl3PSJ9LCJjaXBoZXIiOnsibmFtZSI6Im5hY2wvc2VjcmV0Ym94
    Iiwibm9uY2UiOiJ4RzhOa0RRTnJZNXdtK3FNVzIxVFNiamZmd1NHd25TZyJ9LCJj
    aXBoZXJ0ZXh0IjoiTURROU5HMGxNUUxrbW9nbFlyejZzTlJaNFZWS2ZBK2dKNXpn
    dzdGZ1FudlUxWVJDSk9HUDZqMlFGdjExVHlZQnkzVmtSK3c2SThJc3A0dk4yTzNO
    UjErVE1qS3NNa3grS2Q4T3doZ1N5ODJQVzZNV0dDdGw3ME5Ea3Q2ODJvTDBLUzhF
    REZJOFBlWnoxaW4rNVM4MTM0M25MWlNDWjNEWTNHcUtzNzZPSEN1ck5WaVNPeGJ3
    MHRCc3Zsa0VxT3lmbk9JdmZmdFVwSnRtUEE9PSJ9
    -----END ENCRYPTED SIGSTORE PRIVATE KEY-----
  cosign.pub: |
    -----BEGIN PUBLIC KEY-----
    MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEuNu3DlQ4fGiaFUVYnd4XjYsLyeuB
    80COLJMtFkd5cay7rIcgV+LDvOJVt88Zzl0SJRXqev+iz8a99OmCdzMa3w==
    -----END PUBLIC KEY-----
  cosign.password: ""
