apiVersion: hypershift.openshift.io/v1beta1
kind: HostedCluster
metadata:
  name: payu-dev
  namespace: clusters
  labels:
    app.kubernetes.io/part-of: payu
    environment: dev
spec:
  channel: stable-4.21
  release:
    image: quay.io/openshift-release-dev/ocp-release:4.21.0-multi
  dns:
    baseDomain: sandbox2356.opentlc.com
    privateZoneID: Z01264821HUT3TZSZKLAU
    publicZoneID: Z02597472Z6C8KKS12MZJ
  platform:
    aws:
      region: us-east-1
      endpointAccess: Public
      multiArch: false
      cloudProviderConfig:
        subnet:
          id: subnet-086607bb7577c1092
        vpc: vpc-0d02f6e0681e55e2b
        zone: us-east-1a
      rolesRef:
        controlPlaneOperatorARN: arn:aws:iam::579147609200:role/payu-dev-control-plane-operator
        imageRegistryARN: arn:aws:iam::579147609200:role/payu-dev-openshift-image-registry
        ingressARN: arn:aws:iam::579147609200:role/payu-dev-openshift-ingress
        kubeCloudControllerARN: arn:aws:iam::579147609200:role/payu-dev-cloud-controller
        networkARN: arn:aws:iam::579147609200:role/payu-dev-cloud-network-config-controller
        nodePoolManagementARN: arn:aws:iam::579147609200:role/payu-dev-node-pool
        storageARN: arn:aws:iam::579147609200:role/payu-dev-aws-ebs-csi-driver-controller
      resourceTags:
        - key: kubernetes.io/cluster/payu-dev
          value: owned
        - key: app.kubernetes.io/part-of
          value: payu
        - key: environment
          value: dev
        - key: cost-center
          value: platform-engineering
        - key: owner
          value: payu-team
    type: AWS
  networking:
    clusterNetwork:
      - cidr: 10.136.0.0/14
    machineNetwork:
      - cidr: 10.0.0.0/16
    networkType: Other
    serviceNetwork:
      - cidr: 172.32.0.0/16
  infraID: payu-dev
  fips: false
  issuerURL: https://oidc-storage-payu-dev-579147609200.s3.us-east-1.amazonaws.com/payu-dev
  configuration:
    ingress:
      loadBalancer:
        platform:
          aws:
            type: NLB
  capabilities: {}
  olmCatalogPlacement: management
  services:
    - service: APIServer
      servicePublishingStrategy:
        type: LoadBalancer
    - service: OAuthServer
      servicePublishingStrategy:
        type: Route
    - service: Konnectivity
      servicePublishingStrategy:
        type: Route
    - service: Ignition
      servicePublishingStrategy:
        type: Route
  controllerAvailabilityPolicy: SingleReplica
  infrastructureAvailabilityPolicy: SingleReplica
  autoscaling:
    scaling: ScaleUpAndScaleDown
  etcd:
    managed:
      storage:
        persistentVolume:
          size: 8Gi
          storageClassName: gp3-csi
        type: PersistentVolume
    managementType: Managed
  secretEncryption:
    aescbc:
      activeKey:
        name: payu-dev-etcd-encryption-key
    type: aescbc
  pullSecret:
    name: payu-dev-pull-secret
