apiVersion: hypershift.openshift.io/v1beta1
kind: NodePool
metadata:
  name: payu-onprem
  namespace: clusters
  labels:
    hypershift.openshift.io/cluster: payu-onprem
    app.kubernetes.io/part-of: payu
spec:
  clusterName: payu-onprem
  arch: amd64
  release:
    image: quay.io/openshift-release-dev/ocp-release:4.15.43-multi
  replicas: 2
  management:
    autoRepair: true
    upgradeType: Replace
  platform:
    aws:
      instanceType: m6a.4xlarge
      instanceProfile: payu-onprem-worker
      rootVolume:
        size: 120
        type: gp3
      subnet:
        id: subnet-01c05cd3ccb615f35
      resourceTags:
        - key: kubernetes.io/cluster/payu-onprem
          value: owned
        - key: app.kubernetes.io/part-of
          value: payu
        - key: environment
          value: onprem
        - key: cost-center
          value: platform-engineering
        - key: owner
          value: payu-team
    type: AWS
