apiVersion: hypershift.openshift.io/v1beta1
kind: NodePool
metadata:
  name: payu-dev
  namespace: clusters
  labels:
    hypershift.openshift.io/cluster: payu-dev
    app.kubernetes.io/part-of: payu
spec:
  clusterName: payu-dev
  arch: amd64
  release:
    image: quay.io/openshift-release-dev/ocp-release:4.21.0-multi

  replicas: 2

  management:
    autoRepair: false
    upgradeType: Replace

  platform:
    aws:
      instanceType: m6a.2xlarge
      instanceProfile: payu-dev-worker
      rootVolume:
        size: 120
        type: gp3
      subnet:
        id: subnet-086607bb7577c1092
      resourceTags:
        - key: kubernetes.io/cluster/payu-dev
          value: owned
        - key: app.kubernetes.io/part-of
          value: payu
        - key: environment
          value: dev
        - key: cost-center
          value: platform-engineering
        - key: owner
          value: payu-team
    type: AWS
