apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: payu
resources:
  - ../../../base/web-app
images:
  - name: image-registry.openshift-image-registry.svc:5000/payu-dev/web-app
    newName: image-registry.openshift-image-registry.svc:5000/payu/web-app
    newTag: "1.18.32"
