apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: payu
resources:
  - ../../../base/billing-service
images:
  - name: image-registry.openshift-image-registry.svc:5000/payu-dev/billing-service
    newName: image-registry.openshift-image-registry.svc:5000/payu/billing-service
    newTag: "1.18.40"
