apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: payu
resources:
  - ../../../base/statement-service
images:
  - name: image-registry.openshift-image-registry.svc:5000/payu-dev/statement-service
    newName: image-registry.openshift-image-registry.svc:5000/payu/statement-service
    newTag: "1.18.39"
