apiVersion: v1
kind: ConfigMap
metadata:
  name: pagerduty-config
  namespace: openshift-monitoring
  labels:
    app: payu
    type: alert-integration
data:
  pagerduty-template.yaml: |
    # Alertmanager configuration for PagerDuty integration
    global:
      resolve_timeout: 5m

    templates:
      - '/etc/alertmanager/templates/*.tmpl'

    route:
      group_by: ['alertname', 'cluster', 'service']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 12h
      receiver: 'default'

      routes:
        # Critical alerts go to PagerDuty with high urgency
        - match:
            severity: critical
          receiver: 'pagerduty-critical'
          continue: true

        # SLO breaches go to PagerDuty
        - match_re:
            alertname: 'SLO.*'
          receiver: 'pagerduty-slo'
          continue: true

        # Platform team alerts
        - match:
            team: platform
          receiver: 'pagerduty-platform'
          continue: false

        # Business team alerts during business hours
        - match:
            team: business
          receiver: 'pagerduty-business'
          active_time_intervals:
            - business-hours

    receivers:
      - name: 'default'
        slack_configs:
          - send_resolved: true
            username: 'PayU Alerts'
            channel: '#alerts'
            api_url: 'https://hooks.slack.com/services/YOUR/WEBHOOK/URL'
            title: '{{ .GroupLabels.alertname }}'
            text: >-
              {{ range .Alerts }}
              *Alert:* {{ .Labels.alertname }}
              *Severity:* {{ .Labels.severity }}
              *Summary:* {{ .Annotations.summary }}
              *Description:* {{ .Annotations.description }}
              *Runbook:* {{ .Annotations.runbook }}
              {{ end }}

      - name: 'pagerduty-critical'
        pagerduty_configs:
          - service_key: 'YOUR_PAGERDUTY_SERVICE_KEY'
            severity: 'critical'
            description: '{{ .GroupLabels.alertname }}'
            client: 'PayU Platform'
            client_url: 'https://monitoring.payu.internal'
            details:
              firing: '{{ template "pagerduty.default.instances" .Alerts.Firing }}'
              resolved: '{{ template "pagerduty.default.instances" .Alerts.Resolved }}'
              num_firing: '{{ .Alerts.Firing | len }}'
              num_resolved: '{{ .Alerts.Resolved | len }}'

      - name: 'pagerduty-slo'
        pagerduty_configs:
          - service_key: 'YOUR_PAGERDUTY_SLO_SERVICE_KEY'
            severity: 'error'
            description: 'SLO Breach: {{ .GroupLabels.alertname }}'
            client: 'PayU Platform'
            client_url: 'https://monitoring.payu.internal'

      - name: 'pagerduty-platform'
        pagerduty_configs:
          - service_key: 'YOUR_PAGERDUTY_PLATFORM_SERVICE_KEY'
            severity: 'warning'
            description: 'Platform Alert: {{ .GroupLabels.alertname }}'

      - name: 'pagerduty-business'
        pagerduty_configs:
          - service_key: 'YOUR_PAGERDUTY_BUSINESS_SERVICE_KEY'
            severity: 'info'
            description: 'Business Alert: {{ .GroupLabels.alertname }}'

    time_intervals:
      - name: business-hours
        time_intervals:
          - times:
              - start_time: 09:00
                end_time: 17:00
            weekdays: ['monday:friday']

    inhibit_rules:
      # Inhibit warning if critical is firing for the same alert
      - source_match:
          severity: 'critical'
        target_match:
          severity: 'warning'
        equal: ['alertname', 'instance', 'job']

      # Inhibit SLO alerts if there's a critical availability issue
      - source_match:
          alertname: 'SLOAvailabilityBreached'
        target_match_re:
          alertname: 'SLO.*'
        equal: ['service']
---
apiVersion: v1
kind: Secret
metadata:
  name: pagerduty-secrets
  namespace: openshift-monitoring
  labels:
    app: payu
    type: alert-integration
stringData:
  # Critical incidents (24/7 on-call)
  PAGERDUTY_SERVICE_KEY_CRITICAL: "your-critical-service-key-here"

  # SLO breaches (24/7 on-call)
  PAGERDUTY_SERVICE_KEY_SLO: "your-slo-service-key-here"

  # Platform team (24/7 on-call)
  PAGERDUTY_SERVICE_KEY_PLATFORM: "your-platform-service-key-here"

  # Business team (business hours only)
  PAGERDUTY_SERVICE_KEY_BUSINESS: "your-business-service-key-here"
type: Opaque
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alert-templates
  namespace: openshift-monitoring
  labels:
    app: payu
    type: alert-templates
data:
  default.tmpl: |
    {{ define "pagerduty.default.instances" -}}
      {{ range . -}}
        {{ .Labels.instance }}
      {{ end -}}
    {{- end }}

    {{ define "slack.default.title" -}}
      [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .GroupLabels.alertname }}
    {{- end }}

    {{ define "slack.default.text" -}}
      {{ range .Alerts }}
      *Alert:* {{ .Labels.alertname }}
      *Severity:* {{ .Labels.severity }}
      *Summary:* {{ .Annotations.summary }}
      *Description:* {{ .Annotations.description }}
      *Runbook:* {{ .Annotations.runbook }}
      {{ end }}
    {{- end }}

    {{ define "email.default.subject" -}}
      {{ .GroupLabels.alertname }} - {{ .Status | toUpper }}
    {{- end }}

    {{ define "email.default.html" -}}
      <!DOCTYPE html>
      <html>
      <head>
        <style>
          body { font-family: Arial, sans-serif; }
          .alert { margin: 10px 0; padding: 10px; border-left: 4px solid #ff0000; }
          .alert.critical { border-color: #ff0000; }
          .alert.warning { border-color: #ffa500; }
          .alert.info { border-color: #008000; }
          .label { font-weight: bold; }
        </style>
      </head>
      <body>
        <h2>{{ .GroupLabels.alertname }}</h2>
        {{ range .Alerts }}
        <div class="alert {{ .Labels.severity }}">
          <p><span class="label">Severity:</span> {{ .Labels.severity }}</p>
          <p><span class="label">Summary:</span> {{ .Annotations.summary }}</p>
          <p><span class="label">Description:</span> {{ .Annotations.description }}</p>
          <p><span class="label">Runbook:</span> <a href="{{ .Annotations.runbook }}">View Runbook</a></p>
          <p><span class="label">Time:</span> {{ .StartsAt }}</p>
        </div>
        {{ end }}
      </body>
      </html>
    {{- end }}
