apiVersion: v1
kind: ServiceAccount
metadata:
  name: transaction-service
  labels:
    app.kubernetes.io/name: transaction-service
    app.kubernetes.io/part-of: payu
    app.kubernetes.io/component: backend
automountServiceAccountToken: false
