FROM registry.access.redhat.com/ubi9/openjdk-25-runtime:1.24

ARG APP_VERSION=1.8.1
LABEL maintainer="backend-team@payu.fajjjar.my.id"
LABEL org.opencontainers.image.title="payu-api-portal-service"
LABEL org.opencontainers.image.version="${APP_VERSION}"
LABEL org.opencontainers.image.vendor="PayU Indonesia"

USER 185
WORKDIR /deployments
COPY --chown=185 target/quarkus-app/lib/ /deployments/lib/
COPY --chown=185 target/quarkus-app/quarkus-run.jar /deployments/quarkus-run.jar
COPY --chown=185 target/quarkus-app/app/ /deployments/app/
COPY --chown=185 target/quarkus-app/quarkus/ /deployments/quarkus/
EXPOSE 8080

ENV JAVA_OPTS="-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0 -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
HEALTHCHECK --interval=30s --timeout=3s --start-period=90s --retries=3 \
    CMD curl -sf http://localhost:8080/q/health/live || exit 1
ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar /deployments/quarkus-run.jar"]
