server:
  port: 8085

spring:
  application:
    name: partner-service
  datasource:
    url: jdbc:postgresql://localhost:5432/payu_partner
    username: payu
    password: payu
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    serialization:
      write-dates-as-timestamps: false

springdoc:
  api-docs:
    path: /q/openapi
  swagger-ui:
    path: /q/swagger-ui
    operations-sorter: alpha
    tags-sorter: alpha

# Custom properties
partner:
  jwt:
    secret: "payu-snap-bi-secret-key-for-jwt-token-generation-validation-2024-payu-payu"
    expiration-ms: 900000 # 15 minutes

logging:
  level:
    id.payu.partner: INFO
    org.springframework.web: INFO
