apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-3scale-ingress
  namespace: payu-api-management
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector: {} # Allow all pods in the same namespace to communicate with each other
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-openshift-router-to-3scale
  namespace: payu-api-management
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: openshift-ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-3scale-operator-ingress
  namespace: payu-api-management
spec:
  podSelector:
    matchLabels:
      threescale_component: system
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: openshift-operators
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: payu-api-management
      ports:
        - protocol: TCP
          port: 3000
