apiVersion: apps.3scale.net/v1alpha1
kind: APIManager
metadata:
  name: payu-3scale
  namespace: payu-dev
spec:
  wildcardDomain: apps.payu.ocp.fajjjar.my.id
  system:
    appSpec:
      replicas: 1
    sidekiqSpec:
      replicas: 1
  apicast:
    productionSpec:
      replicas: 1
    stagingSpec:
      replicas: 1
  resourceRequirementsEnabled: false
