apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: system-seed
  namespace: payu-api-management
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: payu-vault
    kind: ClusterSecretStore
  target:
    name: system-seed
    creationPolicy: Owner
    template:
      metadata:
        labels:
          app: payu-3scale
          threescale_component: system
  dataFrom:
    - extract:
        key: payu/dev/3scale/system-seed
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: system-database
  namespace: payu-api-management
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: payu-vault
    kind: ClusterSecretStore
  target:
    name: system-database
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: payu/dev/3scale/system-database
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backend-redis
  namespace: payu-api-management
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: payu-vault
    kind: ClusterSecretStore
  target:
    name: backend-redis
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: payu/dev/3scale/backend-redis
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: system-redis
  namespace: payu-api-management
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: payu-vault
    kind: ClusterSecretStore
  target:
    name: system-redis
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: payu/dev/3scale/system-redis
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: redis-3scale-credentials
  namespace: payu-api-management
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: payu-vault
    kind: ClusterSecretStore
  target:
    name: redis-3scale-credentials
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: payu/dev/3scale/redis-3scale-credentials
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: apicast-payu-env
  namespace: payu-api-management
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: payu-vault
    kind: ClusterSecretStore
  target:
    name: apicast-payu-env
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: payu/dev/3scale/apicast-payu-env
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: system-events-hook
  namespace: payu-api-management
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: payu-vault
    kind: ClusterSecretStore
  target:
    name: system-events-hook
    creationPolicy: Owner
    template:
      metadata:
        labels:
          app: payu-3scale
          threescale_component: system
  dataFrom:
    - extract:
        key: payu/dev/3scale/system-events-hook
