apiVersion: v1
kind: Secret
metadata:
  name: system-seed
  namespace: payu-api-management
type: Opaque
stringData:
  # Prefix only. The operator appends spec.wildcardDomain.
  MASTER_DOMAIN: master
  MASTER_USER: admin
  MASTER_PASSWORD: <MASTER_PASSWORD>
  MASTER_ACCESS_TOKEN: <MASTER_ACCESS_TOKEN>
  ADMIN_ACCESS_TOKEN: <ADMIN_ACCESS_TOKEN>
  TENANT_NAME: payu
---
apiVersion: v1
kind: Secret
metadata:
  name: system-database
  namespace: payu-api-management
type: Opaque
stringData:
  URL: <SYSTEM_DATABASE_URL>
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-redis
  namespace: payu-api-management
type: Opaque
stringData:
  REDIS_STORAGE_URL: <BACKEND_REDIS_STORAGE_URL>
  REDIS_QUEUES_URL: <BACKEND_REDIS_QUEUES_URL>
---
apiVersion: v1
kind: Secret
metadata:
  name: system-redis
  namespace: payu-api-management
type: Opaque
stringData:
  URL: <SYSTEM_REDIS_URL>
---
apiVersion: v1
kind: Secret
metadata:
  name: apicast-payu-env
  namespace: payu-api-management
type: Opaque
stringData:
  # Add custom environment variables for APIcast here if needed
  HTTP_CLIENT_TIMEOUT: "10"
---
apiVersion: v1
kind: Secret
metadata:
  name: system-events-hook
  namespace: payu-api-management
type: Opaque
stringData:
  URL: http://system-provider.payu-api-management.svc.cluster.local:3000/admin/api/webhooks
  PASSWORD: <SYSTEM_EVENTS_HOOK_PASSWORD>
