apiVersion: v1
kind: Secret
metadata:
  name: payu-secrets
  namespace: payu
type: Opaque
stringData:
  JWT_SECRET: dummy-jwt-secret-for-prod-32chars-long-12345
  WEBHOOK_SECRET: dummy-webhook-secret
  ENCRYPTION_KEY: dummy-encryption-key-32chars
  ENCRYPTION_SALT: PayU-PROD-PBKDF2-Salt-v3-2026-!SafeForDevOnly!
  secret-key: PayU-PROD-SecretKey-2026-!SafeForDevOnly!
  encryption-key: PayU-PROD-PBKDF2-Salt-v3-2026-!SafeForDevOnly!
  BLIND_INDEX_KEY: PayU-PROD-BlindIndexKey-2026-32BytesLongSecret!
  BLIND_INDEX_PREVIOUS_KEYS: ''
  ENCRYPTION_PREVIOUS_KEYS: ''
---
apiVersion: v1
kind: Secret
metadata:
  name: payu-cache-credentials
  namespace: payu
type: Opaque
stringData:
  username: developer
  password: dev-infinispan-password-2026!
  identities.yaml: "credentials:\n  - username: developer\n    password: dev-infinispan-password-2026!\n"
---
apiVersion: v1
kind: Secret
metadata:
  name: payu-cache-client-tls
  namespace: payu
type: Opaque
stringData:
  tls.crt: ''
  tls.key: ''
  ca.crt: ''
  truststore-password: changeit
---
apiVersion: v1
kind: Secret
metadata:
  name: payu-broker-credentials-secret
  namespace: payu
type: Opaque
stringData:
  AMQ_USER: admin
  AMQ_PASSWORD: admin-password-2026
  AMQ_CLUSTER_USER: cluster-admin
  AMQ_CLUSTER_PASSWORD: cluster-password-2026
