apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - config/configmaps.yaml
  - secrets/secrets-template.yaml
  - monitoring/hpa.yaml

namespace: payu-prod

# Production: use values as-is from base (2 replicas default, gateway=3)
# HPA will scale up based on load
