apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: payu
resources:
  - ../../../base/notification-service
images:
  - name: image-registry.openshift-image-registry.svc:5000/payu-dev/notification-service
    newName: image-registry.openshift-image-registry.svc:5000/payu/notification-service
    newTag: "1.18.19"
