FROM registry.access.redhat.com/ubi9/openjdk-21-runtime:1.24-2
COPY target/qris-simulator-1.0.0-SNAPSHOT-runner.jar /deployments/app.jar
WORKDIR /deployments
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/deployments/app.jar"]
