apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: payu
resources:
  - ../../../base/cms-service
images:
  - name: image-registry.openshift-image-registry.svc:5000/payu-dev/cms-service
    newName: image-registry.openshift-image-registry.svc:5000/payu/cms-service
    newTag: "1.18.33"
