apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: bi-fast-simulator-build-
  namespace: payu-cicd
  labels:
    app: payu
    service: bi-fast-simulator
    type: build
spec:
  pipelineRef:
    name: bi-fast-simulator-pipeline
  params:
    - name: service-name
      value: bi-fast-simulator
    - name: git-url
      value: https://github.com/fajjarnr/payu.git
    - name: git-revision
      value: main
    - name: image
      value: image-registry.openshift-image-registry.svc:5000/payu-dev/bi-fast-simulator
    - name: image-tag
      value: "1.18.37"
    - name: target-env
      value: "dev"
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
    - name: dockerconfig
      secret:
        secretName: dockerconfig
    - name: m2-cache
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: signing-secrets
      secret:
        secretName: signing-secrets
    - name: git-ssh
      secret:
        secretName: git-ssh-credentials
    - name: maven-settings
      secret:
        secretName: maven-settings

