package id.payu.partner.adapter.persistence.entity;

import id.payu.partner.domain.*;

import id.payu.security.multitenancy.TenantAware;
import id.payu.security.multitenancy.TenantEntityListener;
import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.UUID;

/**
 * Represents a shareable payment link / invoice generated by a partner.
 * Payers open the link, select a payment method, and pay.
 */
@Entity
@Table(name = "payment_links",
       indexes = {
           @Index(name = "idx_payment_link_slug", columnList = "slug", unique = true),
           @Index(name = "idx_payment_link_partner", columnList = "partner_id"),
           @Index(name = "idx_payment_link_status", columnList = "status"),
           @Index(name = "idx_payment_link_tenant_id", columnList = "tenant_id"),
           @Index(name = "idx_payment_link_expires_at", columnList = "expires_at")
       })
@TenantAware
@EntityListeners(TenantEntityListener.class)
public class PaymentLinkEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @NotBlank
    @Column(nullable = false, unique = true, length = 36)
    private String slug;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "partner_id", nullable = false)
    private PartnerEntity partner;

    @NotNull
    @Column(nullable = false, precision = 19, scale = 2)
    private BigDecimal amount;

    @NotBlank
    @Column(nullable = false, length = 3)
    private String currency;

    @NotBlank
    @Column(nullable = false, length = 500)
    private String description;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private PaymentLinkStatus status;

    @Column(name = "customer_name", length = 200)
    private String customerName;

    @Column(name = "customer_email", length = 200)
    private String customerEmail;

    @Column(name = "external_id", length = 200)
    private String externalId;

    @Column(name = "callback_url", length = 500)
    private String callbackUrl;

    @Column(name = "redirect_url", length = 500)
    private String redirectUrl;

    @Column(name = "paid_at")
    private LocalDateTime paidAt;

    @Column(name = "payment_method", length = 50)
    private String paymentMethod;

    @Column(name = "payment_reference", length = 100)
    private String paymentReference;

    @Column(name = "expires_at", nullable = false)
    private LocalDateTime expiresAt;

    @Column(name = "tenant_id", length = 64)
    private String tenantId;

    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @UpdateTimestamp
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    public PaymentLinkEntity() {
    }

    public PaymentLinkEntity(PartnerEntity partner, BigDecimal amount, String currency,
                       String description, LocalDateTime expiresAt) {
        this.partner = partner;
        this.slug = UUID.randomUUID().toString().replace("-", "").substring(0, 16);
        this.amount = amount;
        this.currency = currency;
        this.description = description;
        this.status = PaymentLinkStatus.ACTIVE;
        this.expiresAt = expiresAt;
    }

    // Domain methods

    public boolean isActive() {
        return status == PaymentLinkStatus.ACTIVE && expiresAt.isAfter(LocalDateTime.now());
    }

    public void markPaid(String paymentMethod, String paymentReference) {
        if (this.status != PaymentLinkStatus.ACTIVE) {
            throw new IllegalStateException("Payment link is not active: " + this.status);
        }
        this.status = PaymentLinkStatus.PAID;
        this.paidAt = LocalDateTime.now();
        this.paymentMethod = paymentMethod;
        this.paymentReference = paymentReference;
    }

    public void markExpired() {
        if (this.status == PaymentLinkStatus.ACTIVE) {
            this.status = PaymentLinkStatus.EXPIRED;
        }
    }

    public void cancel() {
        if (this.status != PaymentLinkStatus.ACTIVE) {
            throw new IllegalStateException("Only active payment links can be cancelled");
        }
        this.status = PaymentLinkStatus.CANCELLED;
    }

    // Getters and setters

    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }

    public String getSlug() { return slug; }
    public void setSlug(String slug) { this.slug = slug; }

    public PartnerEntity getPartner() { return partner; }
    public void setPartner(PartnerEntity partner) { this.partner = partner; }

    public BigDecimal getAmount() { return amount; }
    public void setAmount(BigDecimal amount) { this.amount = amount; }

    public String getCurrency() { return currency; }
    public void setCurrency(String currency) { this.currency = currency; }

    public String getDescription() { return description; }
    public void setDescription(String description) { this.description = description; }

    public PaymentLinkStatus getStatus() { return status; }
    public void setStatus(PaymentLinkStatus status) { this.status = status; }

    public String getCustomerName() { return customerName; }
    public void setCustomerName(String customerName) { this.customerName = customerName; }

    public String getCustomerEmail() { return customerEmail; }
    public void setCustomerEmail(String customerEmail) { this.customerEmail = customerEmail; }

    public String getExternalId() { return externalId; }
    public void setExternalId(String externalId) { this.externalId = externalId; }

    public String getCallbackUrl() { return callbackUrl; }
    public void setCallbackUrl(String callbackUrl) { this.callbackUrl = callbackUrl; }

    public String getRedirectUrl() { return redirectUrl; }
    public void setRedirectUrl(String redirectUrl) { this.redirectUrl = redirectUrl; }

    public LocalDateTime getPaidAt() { return paidAt; }
    public void setPaidAt(LocalDateTime paidAt) { this.paidAt = paidAt; }

    public String getPaymentMethod() { return paymentMethod; }
    public void setPaymentMethod(String paymentMethod) { this.paymentMethod = paymentMethod; }

    public String getPaymentReference() { return paymentReference; }
    public void setPaymentReference(String paymentReference) { this.paymentReference = paymentReference; }

    public LocalDateTime getExpiresAt() { return expiresAt; }
    public void setExpiresAt(LocalDateTime expiresAt) { this.expiresAt = expiresAt; }

    public String getTenantId() { return tenantId; }
    public void setTenantId(String tenantId) { this.tenantId = tenantId; }

    public LocalDateTime getCreatedAt() { return createdAt; }
    public void setCreatedAt(LocalDateTime createdAt) { this.createdAt = createdAt; }

    public LocalDateTime getUpdatedAt() { return updatedAt; }
    public void setUpdatedAt(LocalDateTime updatedAt) { this.updatedAt = updatedAt; }
}
