apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: zerossl-api-certificate
  namespace: openshift-config
spec:
  secretName: api-server-tls-secret-zerossl
  commonName: api.payu.ocp.fajjjar.my.id
  dnsNames:
    - api.payu.ocp.fajjjar.my.id
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  privateKey:
    algorithm: RSA
    size: 2048
    rotationPolicy: Never
  issuerRef:
    name: zerossl-production-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  usages:
    - server auth
    - client auth
