apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: zerossl-ingress-certificate
  namespace: openshift-ingress
spec:
  secretName: app-router-certs-zerossl
  commonName: '*.apps.payu.ocp.fajjjar.my.id'
  dnsNames:
    - '*.apps.payu.ocp.fajjjar.my.id'
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  privateKey:
    algorithm: RSA
    size: 2048
    rotationPolicy: Never
  issuerRef:
    name: zerossl-production-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  usages:
    - server auth
    - client auth
