# Allow External Secrets Operator to access Vault in payu-dev
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-external-secrets-to-vault
  namespace: payu-dev
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: vault
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: openshift-operators
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: external-secrets
      ports:
        - protocol: TCP
          port: 8200
