apiVersion: operator.openshift.io/v1
kind: KubeDescheduler
metadata:
  name: cluster
  namespace: openshift-kube-descheduler-operator
spec:
  logLevel: Normal
  managementState: Managed
  operatorLogLevel: Normal
  deschedulingIntervalSeconds: 300
  profiles:
    - TopologyAndDuplicates
    - LifecycleAndUtilization
    - EvictPodsWithPVC
  mode: Automatic
  profileCustomizations:
    namespaces:
      included:
        - payu-dev
