apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: payu
resources:
  - ../../../base/analytics-service
images:
  - name: image-registry.openshift-image-registry.svc:5000/payu-dev/analytics-service
    newName: image-registry.openshift-image-registry.svc:5000/payu/analytics-service
    newTag: "1.18.42"
