apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: litmus

resources:
  - operator.yaml
  - scc.yaml
  - scc-portal.yaml
  - rbac.yaml
  - litmus-generated.yaml
  - route.yaml
