apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  labels:
    app: analytics-service
    app.kubernetes.io/name: analytics-service
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: payu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
        app.kubernetes.io/name: analytics-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: analytics-service
          image: default-route-openshift-image-registry.apps.cluster.payu.fajjjar.my.id/payu-dev/analytics-service:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          env:
            - name: DATABASE_URL
              value: "postgresql+asyncpg://payu:$(DATABASE_PASSWORD)@payu-postgres-primary:5432/payu_analytics"
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://jaeger:4317"
            - name: SECRET_KEY
              value: "CF2owM6bqkyWHSHCGlxMvx/PwBFQ2XCq4C3kdA7tiqQ="
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "2000m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  labels:
    app: analytics-service
spec:
  selector:
    app: analytics-service
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  type: ClusterIP
