CREATE TABLE kyc_reviews (
    id UUID DEFAULT RANDOM_UUID() PRIMARY KEY,
    user_id VARCHAR NOT NULL,
    user_id_blind_index VARCHAR(64),
    user_id_blind_index_key_version VARCHAR(32),
    account_number VARCHAR NOT NULL,
    document_type VARCHAR(100),
    document_number VARCHAR(200),
    document_url TEXT,
    full_name VARCHAR(100),
    address TEXT,
    phone_number VARCHAR(50),
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    notes TEXT,
    reviewed_by VARCHAR(100),
    reviewed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE fraud_cases (
    id UUID DEFAULT RANDOM_UUID() PRIMARY KEY,
    user_id VARCHAR NOT NULL,
    account_number VARCHAR(100),
    transaction_id UUID,
    transaction_type VARCHAR(50),
    amount DECIMAL(19,4),
    fraud_type VARCHAR(100),
    risk_level VARCHAR(20) NOT NULL DEFAULT 'MEDIUM',
    status VARCHAR(20) NOT NULL DEFAULT 'OPEN',
    description TEXT,
    evidence JSON,
    notes TEXT,
    assigned_to VARCHAR(100),
    resolved_by VARCHAR(100),
    resolved_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE customer_cases (
    id UUID DEFAULT RANDOM_UUID() PRIMARY KEY,
    user_id VARCHAR NOT NULL,
    account_number VARCHAR(100),
    case_number VARCHAR(50),
    case_type VARCHAR(30) NOT NULL,
    priority VARCHAR(20) NOT NULL DEFAULT 'MEDIUM',
    subject VARCHAR(200) NOT NULL,
    description TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'OPEN',
    notes TEXT,
    assigned_to VARCHAR(100),
    resolved_by VARCHAR(100),
    resolved_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE backoffice_admins (
    id UUID DEFAULT RANDOM_UUID() PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR NOT NULL UNIQUE,
    password_hash VARCHAR(255),
    first_name VARCHAR(100),
    last_name VARCHAR(100),
    phone_number VARCHAR(20),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    department VARCHAR(50),
    permissions VARCHAR,
    created_by VARCHAR NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_login_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE outbox_events (
    id UUID DEFAULT RANDOM_UUID() PRIMARY KEY,
    aggregate_type VARCHAR(100) NOT NULL,
    aggregate_id VARCHAR(100) NOT NULL,
    event_type VARCHAR(100) NOT NULL,
    payload JSON NOT NULL,
    headers JSON,
    destination_topic VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    published_at TIMESTAMP WITH TIME ZONE,
    sequence_num BIGINT GENERATED BY DEFAULT AS IDENTITY,
    retry_count INTEGER NOT NULL DEFAULT 0,
    last_error VARCHAR(1000)
);

CREATE INDEX idx_kyc_status ON kyc_reviews(status);
CREATE INDEX idx_fraud_risk ON fraud_cases(risk_level);
CREATE INDEX idx_case_priority ON customer_cases(priority);
CREATE INDEX idx_outbox_aggregate ON outbox_events(aggregate_type, aggregate_id);
CREATE INDEX idx_outbox_published ON outbox_events(published_at);
CREATE INDEX idx_outbox_created ON outbox_events(created_at);
