apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: default
  namespace: openshift-ingress-operator
spec:
  idleConnectionTerminationPolicy: Deferred
  closedClientConnectionPolicy: Continue
  routeSelector:
    matchExpressions:
      - key: hypershift.openshift.io/hosted-control-plane
        operator: DoesNotExist
  tuningOptions:
    reloadInterval: 0s
  clientTLS:
    clientCA:
      name: ''
    clientCertificatePolicy: ''
  unsupportedConfigOverrides: null
  defaultCertificate:
    name: cert-manager-ingress-cert
  httpErrorCodePages:
    name: ''
  replicas: 3
  httpEmptyRequestsPolicy: Respond
  httpCompression: {}
  endpointPublishingStrategy:
    loadBalancer:
      providerParameters:
        aws:
          type: NLB
        type: AWS
      scope: External
    type: LoadBalancerService
