apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: payu-sit
resources:
  - ../../../base/statement-service
images:
  - name: image-registry.openshift-image-registry.svc:5000/payu-dev/statement-service
    newName: image-registry.openshift-image-registry.svc:5000/payu-sit/statement-service
    newTag: "1.18.20"
patches:
  - target:
      kind: Deployment
      name: statement-service
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: SPRINGDOC_API_DOCS_ENABLED
          value: "true"
