apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: payu-sit
resources:
  - ../../../base/va-simulator.yaml
images:
  - name: image-registry.openshift-image-registry.svc:5000/payu-dev/va-simulator
    newName: image-registry.openshift-image-registry.svc:5000/payu-sit/va-simulator
    digest: sha256:b1a5b51b25a7d9fd710cdbd5fe7037e4b042a0be2ddec1bc88c0bdfaf7adb21e
