apiVersion: v1
kind: Service
metadata:
  name: auth-service
  labels:
    app.kubernetes.io/name: auth-service
    app.kubernetes.io/part-of: payu
    app.kubernetes.io/version: 1.8.83
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: auth-service
  ports:
  - port: 8080
    targetPort: 8080
    name: http
