---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: payu-cicd-pipeline-image-builder
  namespace: payu-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:image-builder
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: payu-cicd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: payu-cicd-pipeline-image-builder
  namespace: payu-sit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:image-builder
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: payu-cicd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: payu-cicd-pipeline-image-builder
  namespace: payu-uat
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:image-builder
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: payu-cicd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: payu-cicd-pipeline-image-builder
  namespace: payu-preprod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:image-builder
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: payu-cicd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: payu-cicd-pipeline-image-builder
  namespace: payu
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:image-builder
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: payu-cicd
