apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - rbac.yaml
  - smoke-testrun.yaml
  - crud-stress-testrun.yaml
  - crud-load-testrun.yaml
  - crud-consistency-testrun.yaml
