apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../common

namespace: payu-sit

patches:
  - target:
      kind: Keycloak
      name: payu-keycloak
    patch: |
      - op: add
        path: /spec/hostname/hostname
        value: https://sso-sit.payu.fajjjar.my.id
  - target:
      kind: KeycloakRealmImport
      name: payu-realm-import
    patch: |
      - op: replace
        path: /spec/realm/clients/0/redirectUris
        value:
          - https://sit.payu.fajjjar.my.id/*
      - op: replace
        path: /spec/realm/clients/0/webOrigins
        value:
          - https://sit.payu.fajjjar.my.id
          - "+"