apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: payu-uat
resources:
  - ../../../base/investment-service
images:
  - name: image-registry.openshift-image-registry.svc:5000/payu-dev/investment-service
    newName: image-registry.openshift-image-registry.svc:5000/payu-uat/investment-service
    newTag: "1.18.74"
patches:
  - target:
      kind: Deployment
      name: investment-service
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: SPRINGDOC_API_DOCS_ENABLED
          value: "true"
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: investment-service
      spec:
        template:
          spec:
            containers:
              - name: app
                env:
                  - name: OIDC_ISSUER
                    value: "https://sso-uat.apps.fajjjar.my.id/realms/payu"
                  - name: OIDC_JWK_SET_URI
                    value: "https://sso-uat.apps.fajjjar.my.id/realms/payu/protocol/openid-connect/certs"
