apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: payu-http-redirect
  namespace: istio-system
  labels:
    app.kubernetes.io/part-of: payu
    app.kubernetes.io/component: service-mesh
spec:
  parentRefs:
    - name: payu-public-gateway
      sectionName: http
  hostnames:
    - api.dev.payu.fajjjar.my.id
    - api.sit.payu.fajjjar.my.id
    - api.uat.payu.fajjjar.my.id
    - api.preprod.payu.fajjjar.my.id
    - api.payu.fajjjar.my.id
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            port: 8443
            statusCode: 301

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: payu-gateway-dev
  namespace: payu-dev
  labels:
    app.kubernetes.io/part-of: payu
    app.kubernetes.io/component: service-mesh
spec:
  parentRefs:
    - name: payu-public-gateway
      namespace: istio-system
      sectionName: https
  hostnames:
    - api.dev.payu.fajjjar.my.id
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      filters:
        - type: RequestHeaderModifier
          requestHeaderModifier:
            set:
              - name: X-PayU-Environment
                value: dev
              - name: X-PayU-Ingress
                value: gateway-api
      backendRefs:
        - name: gateway-service
          port: 8080

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: payu-gateway-sit
  namespace: payu-sit
  labels:
    app.kubernetes.io/part-of: payu
    app.kubernetes.io/component: service-mesh
spec:
  parentRefs:
    - name: payu-public-gateway
      namespace: istio-system
      sectionName: https
  hostnames:
    - api.sit.payu.fajjjar.my.id
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      filters:
        - type: RequestHeaderModifier
          requestHeaderModifier:
            set:
              - name: X-PayU-Environment
                value: sit
              - name: X-PayU-Ingress
                value: gateway-api
      backendRefs:
        - name: gateway-service
          port: 8080

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: payu-gateway-uat
  namespace: payu-uat
  labels:
    app.kubernetes.io/part-of: payu
    app.kubernetes.io/component: service-mesh
spec:
  parentRefs:
    - name: payu-public-gateway
      namespace: istio-system
      sectionName: https
  hostnames:
    - api.uat.payu.fajjjar.my.id
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      filters:
        - type: RequestHeaderModifier
          requestHeaderModifier:
            set:
              - name: X-PayU-Environment
                value: uat
              - name: X-PayU-Ingress
                value: gateway-api
      backendRefs:
        - name: gateway-service
          port: 8080

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: payu-gateway-preprod
  namespace: payu-preprod
  labels:
    app.kubernetes.io/part-of: payu
    app.kubernetes.io/component: service-mesh
spec:
  parentRefs:
    - name: payu-public-gateway
      namespace: istio-system
      sectionName: https
  hostnames:
    - api.preprod.payu.fajjjar.my.id
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      filters:
        - type: RequestHeaderModifier
          requestHeaderModifier:
            set:
              - name: X-PayU-Environment
                value: preprod
              - name: X-PayU-Ingress
                value: gateway-api
      backendRefs:
        - name: gateway-service
          port: 8080

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: payu-gateway-prod
  namespace: payu
  labels:
    app.kubernetes.io/part-of: payu
    app.kubernetes.io/component: service-mesh
spec:
  parentRefs:
    - name: payu-public-gateway
      namespace: istio-system
      sectionName: https
  hostnames:
    - api.payu.fajjjar.my.id
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      filters:
        - type: RequestHeaderModifier
          requestHeaderModifier:
            set:
              - name: X-PayU-Environment
                value: prod
              - name: X-PayU-Ingress
                value: gateway-api
      backendRefs:
        - name: gateway-service
          port: 8080
