apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: payu
resources:
  - ../../../base/product-catalog-service
images:
  - name: image-registry.openshift-image-registry.svc:5000/payu-dev/product-catalog-service
    newName: image-registry.openshift-image-registry.svc:5000/payu/product-catalog-service
    newTag: "1.18.31"
