apiVersion: v1
kind: Namespace
metadata:
  name: openshift-logging
  labels:
    name: openshift-logging
    openshift.io/cluster-monitoring: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-operators-redhat
  labels:
    operators.operatorframework.io/projects.marketplace: "true"
