apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-rules
  namespace: openshift-logging
  labels:
    app.kubernetes.io/part-of: payu
data:
  alert-rules.yaml: |
    groups:
      - name: payu-application-alerts
        rules:
          - alert: HighErrorRate
            expr: |
              rate({app_kubernetes_io_part_of="payu", level="error"}[5m]) > 0.1
            for: 5m
            labels:
              severity: critical
              team: backend
            annotations:
              summary: "High error rate detected"
              description: "Error rate is {{ $value }} errors/sec"
          - alert: HighLatency
            expr: |
              histogram_quantile(0.95, 
                sum(rate({app_kubernetes_io_part_of="payu"} | unwrap(duration) [5m])) by (le)
              ) > 5000
            for: 10m
            labels:
              severity: warning
              team: backend
            annotations:
              summary: "High latency detected"
              description: "95th percentile latency is {{ $value }}ms"
          - alert: DatabaseConnectionError
            expr: |
              {app_kubernetes_io_part_of="payu", message=~".*database.*connection.*error"}
            for: 1m
            labels:
              severity: critical
              team: backend
            annotations:
              summary: "Database connection errors"
              description: "Database connection errors detected"
          - alert: ServiceDown
            expr: |
              count_over_time({app_kubernetes_io_part_of="payu"}[5m]) < 1
            for: 5m
            labels:
              severity: critical
              team: sre
            annotations:
              summary: "Service appears to be down"
              description: "No logs received from service in last 5 minutes"
