package id.payu.logging.util;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.slf4j.MDC;

import static org.assertj.core.api.Assertions.assertThat;

class MdcUtilTest {

    private MdcUtil mdcUtil;

    @BeforeEach
    void setUp() {
        mdcUtil = new MdcUtil();
        MDC.clear();
    }

    @AfterEach
    void tearDown() {
        MDC.clear();
    }

    @Nested
    @DisplayName("withCorrelationId (Runnable)")
    class WithCorrelationIdRunnable {

        @Test
        @DisplayName("should set auto-generated correlation ID during runnable")
        void shouldSetAutoGeneratedId() {
            mdcUtil.withCorrelationId(() -> {
                String id = MDC.get("correlation_id");
                assertThat(id).isNotNull().hasSize(32);
            });
        }

        @Test
        @DisplayName("should set specific correlation ID during runnable")
        void shouldSetSpecificId() {
            mdcUtil.withCorrelationId("my-id-123", () -> {
                assertThat(MDC.get("correlation_id")).isEqualTo("my-id-123");
            });
        }

        @Test
        @DisplayName("should restore previous value after runnable")
        void shouldRestorePreviousValue() {
            MDC.put("correlation_id", "old-value");

            mdcUtil.withCorrelationId("temp-value", () -> {
                assertThat(MDC.get("correlation_id")).isEqualTo("temp-value");
            });

            assertThat(MDC.get("correlation_id")).isEqualTo("old-value");
        }

        @Test
        @DisplayName("should remove key when no previous value existed")
        void shouldRemoveWhenNoPrevious() {
            mdcUtil.withCorrelationId("temp", () -> {});

            assertThat(MDC.get("correlation_id")).isNull();
        }

        @Test
        @DisplayName("should restore on exception")
        void shouldRestoreOnException() {
            MDC.put("correlation_id", "safe");

            try {
                mdcUtil.withCorrelationId("unsafe", () -> {
                    throw new RuntimeException("fail");
                });
            } catch (RuntimeException ignored) {}

            assertThat(MDC.get("correlation_id")).isEqualTo("safe");
        }
    }

    @Nested
    @DisplayName("withCorrelationId (Supplier)")
    class WithCorrelationIdSupplier {

        @Test
        @DisplayName("should return supplier result")
        void shouldReturnResult() {
            String result = mdcUtil.withCorrelationId("sup-id", () -> {
                return "result-" + MDC.get("correlation_id");
            });

            assertThat(result).isEqualTo("result-sup-id");
        }
    }

    @Nested
    @DisplayName("Basic operations")
    class BasicOps {

        @Test
        @DisplayName("should put and get values")
        void shouldPutAndGet() {
            mdcUtil.put("test-key", "test-value");
            assertThat(mdcUtil.get("test-key")).isEqualTo("test-value");
        }

        @Test
        @DisplayName("should remove values")
        void shouldRemove() {
            mdcUtil.put("key", "val");
            mdcUtil.remove("key");
            assertThat(mdcUtil.get("key")).isNull();
        }

        @Test
        @DisplayName("should get correlation ID")
        void shouldGetCorrelationId() {
            MDC.put("correlation_id", "cid-123");
            assertThat(mdcUtil.getCorrelationId()).isEqualTo("cid-123");
        }

        @Test
        @DisplayName("should clear all values")
        void shouldClear() {
            mdcUtil.put("a", "1");
            mdcUtil.put("b", "2");
            mdcUtil.clear();
            assertThat(mdcUtil.get("a")).isNull();
            assertThat(mdcUtil.get("b")).isNull();
        }

        @Test
        @DisplayName("should get copy of context map")
        void shouldGetCopy() {
            mdcUtil.put("x", "y");
            var map = mdcUtil.getCopyOfContextMap();
            assertThat(map).containsEntry("x", "y");
        }
    }
}
