apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: payu-gitops
  namespace: openshift-gitops
spec:
  server:
    autoscale:
      enabled: false
    route:
      enabled: true
      tls:
        termination: reencrypt
  resourceExclusions: |
    - apiGroups:
        - tekton.dev
      clusters:
        - '*'
      kinds:
        - TaskRun
        - PipelineRun
  ha:
    enabled: false
  rbac:
    defaultPolicy: role:readonly
    policy: |
      g, payu-admins, role:admin
      g, cluster-admin, role:admin
  repo:
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 256Mi
