apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: payu-kiali
  namespace: istio-system
spec:
  auth:
    strategy: openshift
  deployment:
    namespace: istio-system
    accessible_namespaces:
      - payu-dev
  external_services:
    prometheus:
      url: "https://thanos-querier.openshift-monitoring.svc.cluster.local:9091"
    grafana:
      enabled: false
    istio:
      root_namespace: istio-system
