apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: payu-dev

resources:
  - ../../../base/account-service

images:
  - name: image-registry.openshift-image-registry.svc:5000/payu-dev/account-service
    newName: image-registry.openshift-image-registry.svc:5000/payu-dev/account-service
    newTag: "1.15.1"
