apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: payu-uat
resources:
  - ../../../base/va-simulator.yaml
images:
  - name: image-registry.openshift-image-registry.svc:5000/payu-dev/va-simulator
    newName: image-registry.openshift-image-registry.svc:5000/payu-uat/va-simulator
    newTag: "1.18.51"
