apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: payu-preprod
resources:
  - ../../../base/notification-service
images:
  - name: image-registry.openshift-image-registry.svc:5000/payu-dev/notification-service
    newName: image-registry.openshift-image-registry.svc:5000/payu-preprod/notification-service
    newTag: "1.18.25"
patches:
  - target:
      kind: Deployment
      name: notification-service
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: SPRINGDOC_API_DOCS_ENABLED
          value: "true"
