apiVersion: compliance.openshift.io/v1alpha1
kind: ScanSetting
metadata:
  name: payu-cis-weekly
  namespace: openshift-operators
autoApplyRemediations: false
debug: false
rawResultStorage:
  rotation: 10
  size: 20Gi
  storageClassName: gp3-csi
  pvAccessModes:
    - ReadWriteOnce
roles:
  - worker
  - master
scanTolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
schedule: "0 3 * * 1"
showNotApplicable: false
strictNodeScan: true
---
apiVersion: compliance.openshift.io/v1alpha1
kind: ScanSettingBinding
metadata:
  name: payu-cis-weekly
  namespace: openshift-operators
profiles:
  - apiGroup: compliance.openshift.io/v1alpha1
    kind: Profile
    name: ocp4-cis-node
  - apiGroup: compliance.openshift.io/v1alpha1
    kind: Profile
    name: ocp4-cis
settingsRef:
  apiGroup: compliance.openshift.io/v1alpha1
  kind: ScanSetting
  name: payu-cis-weekly
