apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: payu
resources:
  - ../../../base/loan-origination-process
images:
  - name: image-registry.openshift-image-registry.svc:5000/payu-dev/loan-origination-process
    newName: image-registry.openshift-image-registry.svc:5000/payu/loan-origination-process
    newTag: "1.18.39"
