# Kraken Configuration for PayU Pre-Production Chaos
# Ref: DEVSECOPS_ARCHITECTURE.md §4.3.3
apiVersion: v1
kind: ConfigMap
metadata:
  name: kraken-config
  namespace: payu-preprod
  labels:
    app.kubernetes.io/part-of: payu
    app.kubernetes.io/component: chaos-engineering
data:
  config.yaml: |
    kraken:
      exit_on_failure: true
      publish_kraken_status: true
      signal_state: RUN
      signal_address: 0.0.0.0
      port: 8081
      chaos_scenarios:
        - pod_disruption_scenarios:
            - scenarios/openshift/etcd.yml
            - scenarios/openshift/openshift-apiserver.yml
            - scenarios/openshift/openshift-kube-apiserver.yml

    cerberus:
      cerberus_enabled: true
      cerberus_url: "http://cerberus.payu-preprod.svc.cluster.local:8080"
      check_applicaton_routes: false

    tunings:
      wait_duration: 60
      iterations: 1
      daemon_mode: false

    health_checks:
      interval: 5
      config:
        - url: https://console-openshift-console.apps.payu.ocp.fajjjar.my.id
          exit_on_failure: true
