apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: payu-kafka-console-oidc
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  labels:
    payu.io/vault-environment-path: "true"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: payu-vault
    kind: ClusterSecretStore
  target:
    name: payu-kafka-console-oidc
    creationPolicy: Owner
  data:
    - secretKey: client-secret
      remoteRef:
        key: payu/environment/kafka-console
        property: oidc-client-secret
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: payu-broker-credentials
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  labels:
    payu.io/vault-environment-path: "true"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: payu-vault
    kind: ClusterSecretStore
  target:
    name: payu-broker-credentials-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: payu/environment/messaging/artemis
