apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: payu-kafka-console-oidc
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  labels:
    payu.io/vault-environment-path: "true"
spec:
  vaultAuthRef: payu-vault
  mount: secret
  type: kv-v2
  path: payu/environment/kafka-console
  refreshAfter: 1h
  hmacSecretData: true
  destination:
    name: payu-kafka-console-oidc
    create: true
    overwrite: true
    transformation:
      excludes:
        - .*
      templates:
        client-secret:
          text: '{{ get .Secrets "oidc-client-secret" }}'
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: payu-broker-credentials
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  labels:
    payu.io/vault-environment-path: "true"
spec:
  vaultAuthRef: payu-vault
  mount: secret
  type: kv-v2
  path: payu/environment/messaging/artemis
  refreshAfter: 1h
  hmacSecretData: true
  destination:
    name: payu-broker-credentials-secret
    create: true
    overwrite: true
