apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: payu-uat
resources:
  - ../../../base/analytics-service
images:
  - name: image-registry.openshift-image-registry.svc:5000/payu-dev/analytics-service
    newName: image-registry.openshift-image-registry.svc:5000/payu-uat/analytics-service
    newTag: "1.18.34"
patches:
  - target:
      kind: Deployment
      name: analytics-service
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: SPRINGDOC_API_DOCS_ENABLED
          value: "true"
