apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-secrets-operator
  namespace: payu-sit
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: payu-vault
  namespace: payu-sit
spec:
  address: https://vault.payu-vault.svc.cluster.local:8200
  caCertPath: /etc/pki/payu/service-ca.crt
  skipTLSVerify: false
  timeout: 15s
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: payu-vault
  namespace: payu-sit
spec:
  vaultConnectionRef: payu-vault
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: payu-sit
    serviceAccount: vault-secrets-operator
    audiences:
      - vault
    tokenExpirationSeconds: 600
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-secrets-operator
  namespace: payu-uat
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: payu-vault
  namespace: payu-uat
spec:
  address: https://vault.payu-vault.svc.cluster.local:8200
  caCertPath: /etc/pki/payu/service-ca.crt
  skipTLSVerify: false
  timeout: 15s
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: payu-vault
  namespace: payu-uat
spec:
  vaultConnectionRef: payu-vault
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: payu-uat
    serviceAccount: vault-secrets-operator
    audiences:
      - vault
    tokenExpirationSeconds: 600
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-secrets-operator
  namespace: payu-preprod
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: payu-vault
  namespace: payu-preprod
spec:
  address: https://vault.payu-vault.svc.cluster.local:8200
  caCertPath: /etc/pki/payu/service-ca.crt
  skipTLSVerify: false
  timeout: 15s
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: payu-vault
  namespace: payu-preprod
spec:
  vaultConnectionRef: payu-vault
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: payu-preprod
    serviceAccount: vault-secrets-operator
    audiences:
      - vault
    tokenExpirationSeconds: 600
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-secrets-operator
  namespace: payu
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: payu-vault
  namespace: payu
spec:
  address: https://vault.payu-vault.svc.cluster.local:8200
  caCertPath: /etc/pki/payu/service-ca.crt
  skipTLSVerify: false
  timeout: 15s
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: payu-vault
  namespace: payu
spec:
  vaultConnectionRef: payu-vault
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: payu-prod
    serviceAccount: vault-secrets-operator
    audiences:
      - vault
    tokenExpirationSeconds: 600
