apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  name: payu-rhtas-artifact-storage
  namespace: openshift-cloud-credential-operator
spec:
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: AWSProviderSpec
    statementEntries:
      - effect: Allow
        action:
          - s3:GetBucketLocation
          - s3:ListBucket
          - s3:ListBucketMultipartUploads
        resource: arn:aws:s3:::payu-payu-ghxd9-rhtas-339712853697
      - effect: Allow
        action:
          - s3:GetObject
          - s3:PutObject
          - s3:AbortMultipartUpload
          - s3:ListMultipartUploadParts
        resource: arn:aws:s3:::payu-payu-ghxd9-rhtas-339712853697/*
      - effect: Allow
        action:
          - kms:Decrypt
          - kms:Encrypt
          - kms:GenerateDataKey
          - kms:DescribeKey
        resource: arn:aws:kms:ap-southeast-1:339712853697:key/a3f32c41-f36b-4ef5-8b0c-4a642a806539
  secretRef:
    name: rhtas-aws-credentials
    namespace: trusted-artifact-signer
  serviceAccountNames:
    - securesign-ha-rekor
---
apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  name: payu-rhtas-postgres-backup
  namespace: openshift-cloud-credential-operator
spec:
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: AWSProviderSpec
    statementEntries:
      - effect: Allow
        action:
          - s3:GetBucketLocation
          - s3:ListBucket
          - s3:ListBucketMultipartUploads
        resource: arn:aws:s3:::payu-payu-ghxd9-backups-339712853697
      - effect: Allow
        action:
          - s3:GetObject
          - s3:PutObject
          - s3:DeleteObject
          - s3:AbortMultipartUpload
          - s3:ListMultipartUploadParts
        resource: arn:aws:s3:::payu-payu-ghxd9-backups-339712853697/rhtas-postgres/*
      - effect: Allow
        action:
          - kms:Decrypt
          - kms:Encrypt
          - kms:GenerateDataKey
          - kms:DescribeKey
        resource: arn:aws:kms:ap-southeast-1:339712853697:key/a3f32c41-f36b-4ef5-8b0c-4a642a806539
  secretRef:
    name: rhtas-postgres-aws-credentials
    namespace: trusted-artifact-signer
  serviceAccountNames:
    - rhtas-postgres
