apiVersion: v1
kind: ServiceAccount
metadata:
  name: fx-service
  labels:
    app.kubernetes.io/name: fx-service
    app.kubernetes.io/part-of: payu
    app.kubernetes.io/component: backend
automountServiceAccountToken: false
