apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: payu-runtime-secrets
spec:
  vaultAuthRef: payu-vault
  mount: secret
  type: kv-v2
  path: payu/environment/workloads/runtime
  refreshAfter: 1h
  hmacSecretData: true
  destination:
    name: payu-runtime-secrets
    create: true
    overwrite: true
    transformation:
      excludeRaw: true
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: payu-security-secrets
spec:
  vaultAuthRef: payu-vault
  mount: secret
  type: kv-v2
  path: payu/environment/workloads/runtime
  refreshAfter: 1h
  hmacSecretData: true
  destination:
    name: payu-secrets
    create: true
    overwrite: true
    transformation:
      excludeRaw: true
      includes:
        - ^(JWT_SECRET|BLIND_INDEX_KEY|BLIND_INDEX_PREVIOUS_KEYS|secret-key)$
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: payu-session-secrets
spec:
  vaultAuthRef: payu-vault
  mount: secret
  type: kv-v2
  path: payu/environment/workloads/runtime
  refreshAfter: 1h
  hmacSecretData: true
  destination:
    name: session-secrets
    create: true
    overwrite: true
    transformation:
      excludeRaw: true
      excludes:
        - .*
      templates:
        next-server-actions-encryption-key:
          text: '{{ get .Secrets "encryption-key" }}'
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: payu-cache-client-tls
spec:
  vaultAuthRef: payu-vault
  mount: secret
  type: kv-v2
  path: payu/environment/cache/client-tls
  refreshAfter: 1h
  hmacSecretData: true
  destination:
    name: payu-cache-client-tls
    create: true
    overwrite: true
    transformation:
      excludeRaw: true
      includes:
        - ^(keystore-password|truststore-password)$
      templates:
        keystore.p12:
          text: '{{ get .Secrets "keystore.p12" | b64dec }}'
        truststore.p12:
          text: '{{ get .Secrets "truststore.p12" | b64dec }}'
