apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: payu-kafka-console-oidc
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: payu-vault
    kind: ClusterSecretStore
  target:
    name: payu-kafka-console-oidc
    creationPolicy: Owner
  data:
    - secretKey: client-secret
      remoteRef:
        key: payu/dev/kafka-console
        property: oidc-client-secret
