apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: payu
resources:
  - ../../../base/kyc-service
images:
  - name: image-registry.openshift-image-registry.svc:5000/payu-dev/kyc-service
    newName: image-registry.openshift-image-registry.svc:5000/payu/kyc-service
    newTag: "1.18.50"
