apiVersion: v1
kind: Secret
metadata:
  name: payu-keycloak-admin
  namespace: payu-sso
  labels:
    app.kubernetes.io/component: sso
    app.kubernetes.io/name: payu-keycloak
    app.kubernetes.io/part-of: payu
type: Opaque
stringData:
  username: "admin"
  password: "admin-password-2026!"
---
apiVersion: v1
kind: Secret
metadata:
  name: payu-keycloak-db
  namespace: payu-sso
  labels:
    app.kubernetes.io/component: sso
    app.kubernetes.io/name: payu-keycloak
    app.kubernetes.io/part-of: payu
type: Opaque
stringData:
  username: "payu"
  password: "payu-dev-app-pass-2026"
---
apiVersion: v1
kind: Secret
metadata:
  name: payu-keycloak-client-secrets
  namespace: payu-sso
  labels:
    app.kubernetes.io/component: sso
    app.kubernetes.io/name: payu-keycloak
    app.kubernetes.io/part-of: payu
type: Opaque
stringData:
  payu-backend-client-secret: "payu-backend-secret-dev-2026!"
  payu-web-client-secret: "payu-web-secret-dev-2026!"
