apiVersion: v1
kind: ServiceAccount
metadata:
  name: keycloak-secret-reader
  namespace: payu-sso
  labels:
    app.kubernetes.io/component: secrets
    app.kubernetes.io/name: payu-keycloak
    app.kubernetes.io/part-of: payu
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: payu-dev-keycloak-secret-reader
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames:
      - payu-database-app
      - payu-keycloak-client-secrets
    verbs: ["get"]
  - apiGroups: ["authorization.k8s.io"]
    resources: ["selfsubjectrulesreviews"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: payu-dev-keycloak-secret-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: payu-dev-keycloak-secret-reader
subjects:
  - kind: ServiceAccount
    name: keycloak-secret-reader
    namespace: payu-sso
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: payu-dev-kubernetes-secrets
  namespace: payu-sso
  labels:
    app.kubernetes.io/component: secrets
    app.kubernetes.io/name: payu-keycloak
    app.kubernetes.io/part-of: payu
spec:
  provider:
    kubernetes:
      remoteNamespace: payu-dev
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
      auth:
        serviceAccount:
          name: keycloak-secret-reader
          namespace: payu-sso
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: payu-keycloak-db
  namespace: payu-sso
  labels:
    app.kubernetes.io/component: secrets
    app.kubernetes.io/name: payu-keycloak
    app.kubernetes.io/part-of: payu
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: payu-dev-kubernetes-secrets
    kind: SecretStore
  target:
    name: payu-keycloak-db
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: username
      remoteRef:
        key: payu-database-app
        property: username
    - secretKey: password
      remoteRef:
        key: payu-database-app
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: payu-keycloak-client-secrets
  namespace: payu-sso
  labels:
    app.kubernetes.io/component: secrets
    app.kubernetes.io/name: payu-keycloak
    app.kubernetes.io/part-of: payu
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    name: payu-dev-kubernetes-secrets
    kind: SecretStore
  target:
    name: payu-keycloak-client-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: payu-backend-client-secret
      remoteRef:
        key: payu-keycloak-client-secrets
        property: payu-backend-client-secret
    - secretKey: payu-web-client-secret
      remoteRef:
        key: payu-keycloak-client-secrets
        property: payu-web-client-secret
