apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# PayU Identity - Dev Overlay
# Dev-specific patches for identity infrastructure
# Apply with: oc apply -k infrastructure/platform/identity/overlays/dev/

resources:
  - ../common
  - keycloak-db-secret-sync.yaml

namespace: payu-sso

# Dev-specific patches
patches:
  # Keycloak: Dev (1 instance)
  - target:
      kind: Keycloak
      name: payu-keycloak
    patch: |
      - op: replace
        path: /spec/instances
        value: 1
      - op: replace
        path: /spec/db/host
        value: payu-database-rw.payu-dev.svc.cluster.local
      - op: add
        path: /spec/hostname/hostname
        value: https://sso-payu-dev.apps.payu.ocp.fajjjar.my.id
  - target:
      kind: KeycloakRealmImport
      name: payu-realm-import
    patch: |
      - op: replace
        path: /spec/realm/clients/0/redirectUris
        value:
          - http://localhost:3001/*
          - https://payu-dev.apps.payu.ocp.fajjjar.my.id/*
      - op: replace
        path: /spec/realm/clients/0/webOrigins
        value:
          - http://localhost:3001
          - https://payu-dev.apps.payu.ocp.fajjjar.my.id
          - "+"
