apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: payu
resources:
  - ../../../base/investment-service
images:
  - name: image-registry.openshift-image-registry.svc:5000/payu-dev/investment-service
    newName: image-registry.openshift-image-registry.svc:5000/payu/investment-service
    newTag: "1.18.44"
