# Environment-specific configuration for SIT
spring:
  cloud:
    vault:
      enabled: ${VAULT_ENABLED:true}
  datasource:
    primary:
      jdbc-url: ${DB_URL:jdbc:postgresql://payu-postgres-sit.payu-db-sit.svc.cluster.local:5432/payu_sit}
      username: ${DB_USERNAME:payu_sit_app}
      password: ${DB_PASSWORD}
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS:payu-kafka-sit-kafka-bootstrap.payu-messaging-sit.svc.cluster.local:9092}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OIDC_ISSUER:http://payu-keycloak-sit.payu-sso-sit.svc.cluster.local:8080/realms/payu}
          jwk-set-uri: ${OIDC_JWK_SET_URI:http://payu-keycloak-sit.payu-sso-sit.svc.cluster.local:8080/realms/payu/protocol/openid-connect/certs}

payu:
  gateway:
    url: ${GATEWAY_URL:http://gateway-service-sit:8080}
  cache:
    hotrod:
      server-list: ${PAYU_CACHE_HOTROD_SERVER_LIST}
      cache-name: payu

management:
  otlp:
    tracing:
      endpoint: ${OTEL_ENDPOINT:http://otel-collector-sit.payu-monitoring-sit.svc.cluster.local:4317}
  zipkin:
    tracing:
      endpoint: ${OTEL_ENDPOINT:http://otel-collector-sit.payu-monitoring-sit.svc.cluster.local:4317}/v1/spans
