FROM registry.access.redhat.com/ubi9/openjdk-21-runtime:1.21
ARG APP_VERSION=1.0.0
LABEL maintainer="platform-team@payu.fajjjar.my.id"
USER root
RUN microdnf install -y libacl python3 && microdnf clean all && useradd -u 1001 payu && mkdir -p /deployments && chown -R 1001:0 /deployments
USER 1001
WORKDIR /deployments
COPY target/app.jar /deployments/app.jar
EXPOSE 8080
ENV JAVA_OPTS="-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0"
HEALTHCHECK --interval=30s --timeout=3s --start-period=60s --retries=3 CMD curl -sf http://localhost:8080/actuator/health/liveness || exit 1
ENTRYPOINT ["sh","-c","java $JAVA_OPTS -jar /deployments/app.jar"]
