apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: gitleaks
  namespace: payu-cicd
  labels:
    app.kubernetes.io/part-of: payu
spec:
  description: "Scan code repository for hardcoded secrets using Gitleaks."
  workspaces:
    - name: source
      description: Workspace containing the source code to scan
  stepTemplate:
    securityContext:
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
      seccompProfile:
        type: RuntimeDefault
  steps:
    - name: scan
      image: "zricethezav/gitleaks:v8.18.2"
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        echo "Running Gitleaks Secret Scan..."
        gitleaks detect -v --source . --no-git
        RESULT=$?
        if [ $RESULT -eq 0 ]; then
          echo "[✓] No hardcoded secrets found."
        else
          echo "[✗] Hardcoded secrets detected! Build failed."
          exit $RESULT
        fi
