###############################################################################
# Red Hat build of Keycloak (RHBK) - Secrets
# Bootstrap admin + DB credentials for Keycloak
###############################################################################
---
apiVersion: v1
kind: Secret
metadata:
  name: payu-keycloak-admin
  namespace: payu-dev
  labels:
    app.kubernetes.io/component: sso
    app.kubernetes.io/name: payu-keycloak
    app.kubernetes.io/part-of: payu
type: Opaque
stringData:
  username: admin
  password: EONue7dM1Zx4_Q==
---
apiVersion: v1
kind: Secret
metadata:
  name: payu-keycloak-db
  namespace: payu-dev
  labels:
    app.kubernetes.io/component: sso
    app.kubernetes.io/name: payu-keycloak
    app.kubernetes.io/part-of: payu
type: Opaque
stringData:
  username: payu
  password: "}9/-[a<(+bLLFCvKa2[78JPu"
