apiVersion: v1
baseDomain: ocp.fajjjar.my.id
compute:
  - architecture: amd64
    hyperthreading: Enabled
    name: worker
    platform:
      aws:
        rootVolume:
          size: 100
          type: gp3
        type: m5.4xlarge
        metadataService:
          authentication: Required
        zones:
          - ap-southeast-1a
          - ap-southeast-1b
          - ap-southeast-1c
    replicas: 3
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform:
    aws:
      rootVolume:
        size: 100
        type: gp3
      type: m5.2xlarge
      metadataService:
        authentication: Required
      zones:
        - ap-southeast-1a
        - ap-southeast-1b
        - ap-southeast-1c
  replicas: 3
metadata:
  name: payu
networking:
  machineCIDR: 10.0.0.0/16
  machineNetwork:
    - cidr: 10.0.0.0/16
  clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
  serviceNetwork:
    - 172.30.0.0/16
  networkType: OVNKubernetes
platform:
  aws:
    region: ap-southeast-1
    lbType: NLB
    subnets:
      - subnet-04cf697252c780068
      - subnet-0fcef0f9c65774796
      - subnet-078577e5ff7cb145f
      - subnet-0568db878c4e65b02
      - subnet-046358054e0a9f1e9
      - subnet-0a904e9b9fe840684
publish: External
sshKey: ''
pullSecret: ''
