apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: payu
resources:
  - ../../../base/biller-simulator.yaml
images:
  - name: image-registry.openshift-image-registry.svc:5000/payu-dev/biller-simulator
    newName: image-registry.openshift-image-registry.svc:5000/payu/biller-simulator
    newTag: "1.18.50"
