apiVersion: apps/v1
kind: Deployment
metadata:
  name: integration-service
  labels:
    app.kubernetes.io/name: integration-service
    app.kubernetes.io/part-of: payu
    app.kubernetes.io/component: backend
    app.kubernetes.io/version: 1.7.9
    team: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: integration-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: integration-service
        app.kubernetes.io/part-of: payu
        app.kubernetes.io/component: backend
        app.kubernetes.io/version: 1.7.9
        team: backend
    spec:
      securityContext:
        runAsNonRoot: true
      volumes:
      - name: tmp
        emptyDir: {}
      containers:
      - name: app
        image: image-registry.openshift-image-registry.svc:5000/payu-dev/integration-service:1.7.9
        ports:
        - containerPort: 8080
          name: http
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 15
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: openshift
        - name: SERVER_PORT
          value: '8080'
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: redis-config
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: redis-config
              key: REDIS_PORT
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-credentials
              key: REDIS_PASSWORD
        - name: SPRING_DATA_REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: redis-config
              key: REDIS_HOST
        - name: SPRING_DATA_REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: redis-config
              key: REDIS_PORT
        - name: SPRING_DATA_REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-credentials
              key: REDIS_PASSWORD
