apiVersion: v1
kind: ConfigMap
metadata:
  name: preprod-environment-config
  namespace: payu-preprod
  labels:
    app.kubernetes.io/part-of: payu
data:
  SPRING_PROFILES_ACTIVE: "container"
  LOG_LEVEL: "WARN"
  DB_HOST: "payu-postgres-primary.payu-preprod.svc"
  DB_PORT: "5432"
  REDIS_HOST: "payu-datagrid.payu-preprod.svc"
  REDIS_PORT: "11222"
  KAFKA_BOOTSTRAP_SERVERS: "payu-kafka-bootstrap.payu-preprod.svc:9092"
  KEYCLOAK_URL: "https://sso.preprod.payu.fajjjar.my.id"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.payu-preprod.svc:4317"
