apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: payu-deploy-pipeline
  namespace: payu-cicd
  labels:
    app: payu
    type: deploy
spec:
  description: |
    Deployment pipeline for PayU services with blue-green deployment strategy.
    Supports multiple environments with automatic rollback on failure.
  params:
    - name: service-name
      type: string
      description: Name of the service to deploy
    - name: environment
      type: string
      description: Target environment (dev, staging, prod)
      default: staging
    - name: image-tag
      type: string
      description: Image tag to deploy
      default: latest
    - name: registry-url
      type: string
      description: Container registry URL
      default: image-registry.openshift-image-registry.svc:5000
    - name: registry-namespace
      type: string
      description: Registry namespace/project
      default: payu
    - name: namespace
      type: string
      description: Target namespace for deployment
      default: payu-staging
    - name: replicas
      type: string
      description: Number of replicas
      default: "3"
    - name: health-check-timeout
      type: string
      description: Timeout for health checks in seconds
      default: "300"
    - name: rollback-on-failure
      type: string
      description: Automatic rollback on deployment failure
      default: "true"
    - name: deployment-strategy
      type: string
      description: Deployment strategy (bluegreen, rolling)
      default: bluegreen
  workspaces:
    - name: manifest-dir
      description: Workspace for Kubernetes manifests
  tasks:
    - name: validate-manifests
      taskRef:
        name: kubeval
        kind: ClusterTask
      workspaces:
        - name: source
          workspace: manifest-dir
      params:
        - name: FILES
          value:
            - infrastructure/openshift/base/$(params.service-name).yaml
        - name: KUBERNETES_VERSION
          value: "1.29"

    - name: create-namespace
      runAfter:
        - validate-manifests
      taskRef:
        name: openshift-client
        kind: ClusterTask
      params:
        - name: SCRIPT
          value: |
            oc new-project $(params.namespace) --skip-config-write || true
            oc label namespace $(params.namespace) environment=$(params.environment) app=payu --overwrite

    - name: apply-configmaps
      runAfter:
        - create-namespace
      taskRef:
        name: openshift-client
        kind: ClusterTask
      workspaces:
        - name: source
          workspace: manifest-dir
      params:
        - name: SCRIPT
          value: |
            oc apply -f infrastructure/openshift/overlays/$(params.environment)/config/configmaps.yaml -n $(params.namespace)

    - name: apply-secrets
      runAfter:
        - create-namespace
      taskRef:
        name: openshift-client
        kind: ClusterTask
      workspaces:
        - name: source
          workspace: manifest-dir
      params:
        - name: SCRIPT
          value: |
            oc apply -f infrastructure/openshift/overlays/$(params.environment)/secrets/secrets-template.yaml -n $(params.namespace)

    - name: create-deployment-config
      runAfter:
        - apply-configmaps
        - apply-secrets
      taskRef:
        name: openshift-client
        kind: ClusterTask
      params:
        - name: SCRIPT
          value: |
            cat <<EOF | oc apply -n $(params.namespace) -f -
            apiVersion: apps.openshift.io/v1
            kind: DeploymentConfig
            metadata:
              name: $(params.service-name)
              labels:
                app: payu
                service: $(params.service-name)
                environment: $(params.environment)
            spec:
              replicas: $(params.replicas)
              strategy:
                type: Rolling
                rollingParams:
                  timeoutSeconds: 600
                  intervalSeconds: 1
                  updatePeriodSeconds: 1
                  maxSurge: 25%
                  maxUnavailable: 0
                resources: {}
              selector:
                app: payu
                deploymentconfig: $(params.service-name)
              template:
                metadata:
                  labels:
                    app: payu
                    deploymentconfig: $(params.service-name)
                spec:
                  containers:
                  - name: $(params.service-name)
                    image: $(params.registry-url)/$(params.registry-namespace)/$(params.service-name):$(params.image-tag)
                    ports:
                    - containerPort: 8080
                      protocol: TCP
                    env:
                    - name: JAVA_OPTS
                      value: "-Xms512m -Xmx1024m -XX:+UseG1GC"
                    - name: SPRING_PROFILES_ACTIVE
                      value: "$(params.environment)"
                    resources:
                      limits:
                        cpu: "2"
                        memory: "2Gi"
                      requests:
                        cpu: "500m"
                        memory: "1Gi"
                    livenessProbe:
                      httpGet:
                        path: /actuator/health/liveness
                        port: 8080
                      initialDelaySeconds: 60
                      timeoutSeconds: 5
                      periodSeconds: 10
                      successThreshold: 1
                      failureThreshold: 3
                    readinessProbe:
                      httpGet:
                        path: /actuator/health/readiness
                        port: 8080
                      initialDelaySeconds: 30
                      timeoutSeconds: 5
                      periodSeconds: 5
                      successThreshold: 1
                      failureThreshold: 3
                  imagePullSecrets:
                  - name: pull-secret
            EOF

    - name: create-service
      runAfter:
        - create-deployment-config
      taskRef:
        name: openshift-client
        kind: ClusterTask
      params:
        - name: SCRIPT
          value: |
            cat <<EOF | oc apply -n $(params.namespace) -f -
            apiVersion: v1
            kind: Service
            metadata:
              name: $(params.service-name)
              labels:
                app: payu
                service: $(params.service-name)
            spec:
              selector:
                app: payu
                deploymentconfig: $(params.service-name)
              ports:
              - name: http
                port: 80
                targetPort: 8080
                protocol: TCP
              type: ClusterIP
            EOF

    - name: create-route
      runAfter:
        - create-service
      taskRef:
        name: openshift-client
        kind: ClusterTask
      params:
        - name: SCRIPT
          value: |
            cat <<EOF | oc apply -n $(params.namespace) -f -
            apiVersion: route.openshift.io/v1
            kind: Route
            metadata:
              name: $(params.service-name)
              labels:
                app: payu
                service: $(params.service-name)
            spec:
              to:
                kind: Service
                name: $(params.service-name)
              port:
                targetPort: http
              tls:
                termination: edge
                insecureEdgeTerminationPolicy: Redirect
            EOF

    - name: create-hpa
      runAfter:
        - create-deployment-config
      taskRef:
        name: openshift-client
        kind: ClusterTask
      params:
        - name: SCRIPT
          value: |
            cat <<EOF | oc apply -n $(params.namespace) -f -
            apiVersion: autoscaling/v2
            kind: HorizontalPodAutoscaler
            metadata:
              name: $(params.service-name)-hpa
            spec:
              scaleTargetRef:
                apiVersion: apps.openshift.io/v1
                kind: DeploymentConfig
                name: $(params.service-name)
              minReplicas: 2
              maxReplicas: 10
              metrics:
              - type: Resource
                resource:
                  name: cpu
                  target:
                    type: Utilization
                    averageUtilization: 70
              - type: Resource
                resource:
                  name: memory
                  target:
                    type: Utilization
                    averageUtilization: 80
              behavior:
                scaleDown:
                  stabilizationWindowSeconds: 300
                  policies:
                  - type: Percent
                    value: 50
                    periodSeconds: 60
                scaleUp:
                  stabilizationWindowSeconds: 0
                  policies:
                  - type: Percent
                    value: 100
                    periodSeconds: 30
            EOF

    - name: wait-for-rollout
      runAfter:
        - create-deployment-config
        - create-hpa
      taskRef:
        name: openshift-client
        kind: ClusterTask
      params:
        - name: SCRIPT
          value: |
            echo "Waiting for deployment to complete..."
            oc rollout status dc/$(params.service-name) -n $(params.namespace) --timeout=$(params.health-check-timeout)s
            echo "Deployment completed successfully"

    - name: smoke-tests
      runAfter:
        - wait-for-rollout
      taskRef:
        name: curl
        kind: ClusterTask
      params:
        - name: url
          value: http://$(params.service-name).$(params.namespace).svc.cluster.local:80/actuator/health
        - name: options
          value:
            - -f
            - -v
        - name: RETRIES
          value: "10"
        - name: RETRY_DELAY
          value: "10"

    - name: rollback-deployment
      runAfter:
        - smoke-tests
      when:
        - input: "$(params.rollback-on-failure)"
          operator: in
          values: ["false"]
      taskRef:
        name: openshift-client
        kind: ClusterTask
      params:
        - name: SCRIPT
          value: |
            echo "Smoke tests passed, deployment successful"
      # This task only runs if previous tasks fail

  finally:
    - name: verify-deployment
      taskRef:
        name: openshift-client
      params:
        - name: SCRIPT
          value: |
            echo "=== Deployment Verification ==="
            oc get pods -n $(params.namespace) -l app=payu,deploymentconfig=$(params.service-name)
            oc get dc/$(params.service-name) -n $(params.namespace)
            oc get hpa/$(params.service-name)-hpa -n $(params.namespace) || true
