apiVersion: v1
kind: ServiceAccount
metadata:
  name: web-app
  labels:
    app.kubernetes.io/name: web-app
    app.kubernetes.io/part-of: payu
    app.kubernetes.io/component: frontend
automountServiceAccountToken: false
