apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: account-service
  description: Core Banking - Account Service. User management, account onboarding, eKYC integration, and profile management.
  annotations:
    github.com/project-slug: payu/account-service
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-label-selector: app=account-service
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
  tags:
    - java
    - spring-boot
    - postgresql
    - kafka
    - hexagonal-architecture
spec:
  type: service
  lifecycle: production
  owner: team-backend
  system: payu-core-banking
  dependsOn:
    - component:postgresql
    - component:kafka
    - component:redis
  providesApis:
    - account-api
