FROM registry.redhat.io/ubi9/openjdk-25-runtime@sha256:a0c3ecb2af6e1100394721417ba412a9c9088dfadce53b8d98bb95a7bb4d23ea

ARG APP_VERSION=1.8.104
LABEL maintainer="backend-team@payu.fajjjar.my.id"
LABEL org.opencontainers.image.title="payu-account-service"
LABEL org.opencontainers.image.version="${APP_VERSION}"
LABEL org.opencontainers.image.vendor="PayU Indonesia"

USER root
RUN microdnf install -y \
      glib2-2.68.4-19.el9_8.2 \
      libacl-2.4.0-1.el9_8 \
      python3-3.9.25-7.el9_8.2 \
      python3-libs-3.9.25-7.el9_8.2 && \
    microdnf clean all && \
    useradd -u 1001 payu && \
    mkdir -p /deployments && \
    chown -R 1001:0 /deployments

USER 1001
WORKDIR /deployments
COPY --chown=1001 target/app.jar /deployments/app.jar
EXPOSE 8080

ENV JAVA_OPTS="-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0 -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -Djava.security.egd=file:/dev/./urandom"
HEALTHCHECK --interval=30s --timeout=3s --start-period=90s --retries=3 \
    CMD curl -sf http://localhost:8080/actuator/health/liveness || exit 1
ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar /deployments/app.jar"]
