package id.payu.partner.domain;

import jakarta.persistence.*;
import org.hibernate.annotations.CreationTimestamp;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.UUID;

/**
 * Represents a dynamic QRIS payment request generated by a merchant.
 * Each QR code is unique per transaction with amount and expiry.
 */
@Entity
@Table(name = "merchant_qr_payments",
       indexes = {
           @Index(name = "idx_qr_payment_merchant_id", columnList = "merchant_id"),
           @Index(name = "idx_qr_payment_reference", columnList = "reference_id", unique = true),
           @Index(name = "idx_qr_payment_status", columnList = "status"),
           @Index(name = "idx_qr_payment_expires_at", columnList = "expires_at")
       })
public class MerchantQrPayment {

    public enum QrPaymentStatus {
        PENDING,
        PAID,
        EXPIRED,
        CANCELLED
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "reference_id", nullable = false, unique = true, length = 36)
    private String referenceId;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "merchant_id", nullable = false)
    private Merchant merchant;

    @Column(nullable = false, precision = 19, scale = 2)
    private BigDecimal amount;

    @Column(nullable = false, length = 3)
    private String currency;

    @Column(length = 500)
    private String description;

    @Column(name = "qr_content", nullable = false, length = 1000)
    private String qrContent;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private QrPaymentStatus status;

    @Column(name = "payer_account_id", length = 64)
    private String payerAccountId;

    @Column(name = "payment_reference", length = 100)
    private String paymentReference;

    @Column(name = "paid_at")
    private LocalDateTime paidAt;

    @Column(name = "expires_at", nullable = false)
    private LocalDateTime expiresAt;

    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    public MerchantQrPayment() {
    }

    public MerchantQrPayment(Merchant merchant, BigDecimal amount, String currency,
                             String description, LocalDateTime expiresAt) {
        this.referenceId = UUID.randomUUID().toString();
        this.merchant = merchant;
        this.amount = amount;
        this.currency = currency;
        this.description = description;
        this.status = QrPaymentStatus.PENDING;
        this.expiresAt = expiresAt;
        // QRIS content format: merchant code + amount + reference
        this.qrContent = String.format("QRIS:%s:%s:%s:%s",
                merchant.getMerchantCode(), amount.toPlainString(), currency, referenceId);
    }

    // Domain methods

    public boolean isPending() {
        return status == QrPaymentStatus.PENDING && expiresAt.isAfter(LocalDateTime.now());
    }

    public void markPaid(String payerAccountId, String paymentReference) {
        if (this.status != QrPaymentStatus.PENDING) {
            throw new IllegalStateException("QR payment is not pending: " + this.status);
        }
        this.status = QrPaymentStatus.PAID;
        this.payerAccountId = payerAccountId;
        this.paymentReference = paymentReference;
        this.paidAt = LocalDateTime.now();
    }

    public void markExpired() {
        if (this.status == QrPaymentStatus.PENDING) {
            this.status = QrPaymentStatus.EXPIRED;
        }
    }

    // Getters and setters

    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }

    public String getReferenceId() { return referenceId; }
    public void setReferenceId(String referenceId) { this.referenceId = referenceId; }

    public Merchant getMerchant() { return merchant; }
    public void setMerchant(Merchant merchant) { this.merchant = merchant; }

    public BigDecimal getAmount() { return amount; }
    public void setAmount(BigDecimal amount) { this.amount = amount; }

    public String getCurrency() { return currency; }
    public void setCurrency(String currency) { this.currency = currency; }

    public String getDescription() { return description; }
    public void setDescription(String description) { this.description = description; }

    public String getQrContent() { return qrContent; }
    public void setQrContent(String qrContent) { this.qrContent = qrContent; }

    public QrPaymentStatus getStatus() { return status; }
    public void setStatus(QrPaymentStatus status) { this.status = status; }

    public String getPayerAccountId() { return payerAccountId; }
    public void setPayerAccountId(String payerAccountId) { this.payerAccountId = payerAccountId; }

    public String getPaymentReference() { return paymentReference; }
    public void setPaymentReference(String paymentReference) { this.paymentReference = paymentReference; }

    public LocalDateTime getPaidAt() { return paidAt; }
    public void setPaidAt(LocalDateTime paidAt) { this.paidAt = paidAt; }

    public LocalDateTime getExpiresAt() { return expiresAt; }
    public void setExpiresAt(LocalDateTime expiresAt) { this.expiresAt = expiresAt; }

    public LocalDateTime getCreatedAt() { return createdAt; }
    public void setCreatedAt(LocalDateTime createdAt) { this.createdAt = createdAt; }
}
