apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: payu-keycloak-client-secrets
  namespace: payu-preprod
  annotations:
    payu.io/secret-generation-revision: "2026-08-04-1"
  labels:
    app.kubernetes.io/component: secrets
    app.kubernetes.io/name: payu-keycloak
    app.kubernetes.io/part-of: payu
spec:
  length: 48
  encoding: base64url
  noUpper: false
  allowRepeat: true
  secretKeys:
    - payu-backend-client-secret
    - payu-web-client-secret
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: payu-keycloak-client-secrets
  namespace: payu-preprod
  annotations:
    payu.io/secret-generation-revision: "2026-08-04-1"
  labels:
    app.kubernetes.io/component: secrets
    app.kubernetes.io/name: payu-keycloak
    app.kubernetes.io/part-of: payu
spec:
  refreshPolicy: OnChange
  target:
    name: payu-keycloak-client-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: payu-keycloak-client-secrets
