apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: payu-preprod
resources:
- namespace.yaml
- ../../base
components:
- ../promotion-common
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: workload-environment
  literals:
  - environment=preprod
replacements:
- source:
    kind: ConfigMap
    name: workload-environment
    fieldPath: data.environment
  targets:
  - select:
      group: secrets.hashicorp.com
      version: v1beta1
      kind: VaultStaticSecret
    fieldPaths:
    - spec.path
    options:
      delimiter: /
      index: 1
images:
- name: image-registry.openshift-image-registry.svc:5000/payu-dev/account-service
  newName: image-registry.openshift-image-registry.svc:5000/payu-preprod/account-service
- name: image-registry.openshift-image-registry.svc:5000/payu-dev/analytics-service
  newName: image-registry.openshift-image-registry.svc:5000/payu-preprod/analytics-service
- name: image-registry.openshift-image-registry.svc:5000/payu-dev/api-portal-service
  newName: image-registry.openshift-image-registry.svc:5000/payu-preprod/api-portal-service
- name: image-registry.openshift-image-registry.svc:5000/payu-dev/auth-service
  newName: image-registry.openshift-image-registry.svc:5000/payu-preprod/auth-service
- name: image-registry.openshift-image-registry.svc:5000/payu-dev/backoffice-service
  newName: image-registry.openshift-image-registry.svc:5000/payu-preprod/backoffice-service
- name: image-registry.openshift-image-registry.svc:5000/payu-dev/billing-service
  newName: image-registry.openshift-image-registry.svc:5000/payu-preprod/billing-service
- name: image-registry.openshift-image-registry.svc:5000/payu-dev/cms-service
  newName: image-registry.openshift-image-registry.svc:5000/payu-preprod/cms-service
- name: image-registry.openshift-image-registry.svc:5000/payu-dev/compliance-service
  newName: image-registry.openshift-image-registry.svc:5000/payu-preprod/compliance-service
- name: image-registry.openshift-image-registry.svc:5000/payu-dev/dispute-service
  newName: image-registry.openshift-image-registry.svc:5000/payu-preprod/dispute-service
- name: image-registry.openshift-image-registry.svc:5000/payu-dev/fx-service
  newName: image-registry.openshift-image-registry.svc:5000/payu-preprod/fx-service
- name: image-registry.openshift-image-registry.svc:5000/payu-dev/gateway-service
  newName: image-registry.openshift-image-registry.svc:5000/payu-preprod/gateway-service
- name: image-registry.openshift-image-registry.svc:5000/payu-dev/integration-service
  newName: image-registry.openshift-image-registry.svc:5000/payu-preprod/integration-service
- name: image-registry.openshift-image-registry.svc:5000/payu-dev/investment-service
  newName: image-registry.openshift-image-registry.svc:5000/payu-preprod/investment-service
- name: image-registry.openshift-image-registry.svc:5000/payu-dev/kyc-service
  newName: image-registry.openshift-image-registry.svc:5000/payu-preprod/kyc-service
- name: image-registry.openshift-image-registry.svc:5000/payu-dev/lending-service
  newName: image-registry.openshift-image-registry.svc:5000/payu-preprod/lending-service
- name: image-registry.openshift-image-registry.svc:5000/payu-dev/notification-service
  newName: image-registry.openshift-image-registry.svc:5000/payu-preprod/notification-service
- name: image-registry.openshift-image-registry.svc:5000/payu-dev/partner-service
  newName: image-registry.openshift-image-registry.svc:5000/payu-preprod/partner-service
- name: image-registry.openshift-image-registry.svc:5000/payu-dev/product-catalog-service
  newName: image-registry.openshift-image-registry.svc:5000/payu-preprod/product-catalog-service
- name: image-registry.openshift-image-registry.svc:5000/payu-dev/promotion-service
  newName: image-registry.openshift-image-registry.svc:5000/payu-preprod/promotion-service
- name: image-registry.openshift-image-registry.svc:5000/payu-dev/statement-service
  newName: image-registry.openshift-image-registry.svc:5000/payu-preprod/statement-service
- name: image-registry.openshift-image-registry.svc:5000/payu-dev/support-service
  newName: image-registry.openshift-image-registry.svc:5000/payu-preprod/support-service
- name: image-registry.openshift-image-registry.svc:5000/payu-dev/transaction-service
  newName: image-registry.openshift-image-registry.svc:5000/payu-preprod/transaction-service
- name: image-registry.openshift-image-registry.svc:5000/payu-dev/wallet-service
  newName: image-registry.openshift-image-registry.svc:5000/payu-preprod/wallet-service
- name: image-registry.openshift-image-registry.svc:5000/payu-dev/web-app
  newName: image-registry.openshift-image-registry.svc:5000/payu-preprod/web-app
- name: image-registry.openshift-image-registry.svc:5000/payu-dev/bi-fast-simulator
  newName: image-registry.openshift-image-registry.svc:5000/payu-preprod/bi-fast-simulator
- name: image-registry.openshift-image-registry.svc:5000/payu-dev/biller-simulator
  newName: image-registry.openshift-image-registry.svc:5000/payu-preprod/biller-simulator
- name: image-registry.openshift-image-registry.svc:5000/payu-dev/dukcapil-simulator
  newName: image-registry.openshift-image-registry.svc:5000/payu-preprod/dukcapil-simulator
- name: image-registry.openshift-image-registry.svc:5000/payu-dev/qris-simulator
  newName: image-registry.openshift-image-registry.svc:5000/payu-preprod/qris-simulator
- name: image-registry.openshift-image-registry.svc:5000/payu-dev/va-simulator
  newName: image-registry.openshift-image-registry.svc:5000/payu-preprod/va-simulator
- name: image-registry.openshift-image-registry.svc:5000/payu-dev/lending-rules
  newName: image-registry.openshift-image-registry.svc:5000/payu-preprod/lending-rules
- name: image-registry.openshift-image-registry.svc:5000/payu-dev/loan-origination-process
  newName: image-registry.openshift-image-registry.svc:5000/payu-preprod/loan-origination-process
patches:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: "^(account-service|analytics-service|api-portal-service|auth-service|backoffice-service|billing-service|cms-service|compliance-service|dispute-service|fx-service|gateway-service|integration-service|investment-service|kyc-service|lending-rules|lending-service|loan-origination-process|notification-service|partner-service|product-catalog-service|promotion-service|statement-service|support-service|transaction-service|wallet-service|web-app)$"
  patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: environment-endpoints
    spec:
      template:
        spec:
          containers:
            - name: app
              env:
                - name: PAYU_CACHE_HOTROD_SNI_HOST_NAME
                  value: payu-cache.payu-preprod.svc.cluster.local
                - name: OIDC_ISSUER
                  value: https://sso.preprod.payu.fajjjar.my.id/realms/payu
                - name: OIDC_JWK_SET_URI
                  value: https://sso.preprod.payu.fajjjar.my.id/realms/payu/protocol/openid-connect/certs
                - name: QUARKUS_OIDC_AUTH_SERVER_URL
                  value: https://sso.preprod.payu.fajjjar.my.id/realms/payu
                - name: QUARKUS_OIDC_TOKEN_ISSUER
                  value: https://sso.preprod.payu.fajjjar.my.id/realms/payu
                - name: PAYU_KEYCLOAK_SERVER_URL
                  value: https://sso.preprod.payu.fajjjar.my.id
- target:
    kind: Route
    name: web-app
  patch: |-
    apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      name: web-app
      labels:
        ingress.payu.io/class: shared
    spec:
      host: app-preprod.apps.fajjjar.my.id
- target:
    kind: Deployment
    name: account-service
  patch: '[{"op": "replace", "path": "/spec/replicas", "value": 2}]'
- target:
    kind: Deployment
    name: analytics-service
  patch: '[{"op": "replace", "path": "/spec/replicas", "value": 2}]'
- target:
    kind: Deployment
    name: api-portal-service
  patch: '[{"op": "replace", "path": "/spec/replicas", "value": 2}]'
- target:
    kind: Deployment
    name: auth-service
  patch: '[{"op": "replace", "path": "/spec/replicas", "value": 2}]'
- target:
    kind: Deployment
    name: backoffice-service
  patch: '[{"op": "replace", "path": "/spec/replicas", "value": 2}]'
- target:
    kind: Deployment
    name: billing-service
  patch: '[{"op": "replace", "path": "/spec/replicas", "value": 2}]'
- target:
    kind: Deployment
    name: cms-service
  patch: '[{"op": "replace", "path": "/spec/replicas", "value": 2}]'
- target:
    kind: Deployment
    name: compliance-service
  patch: '[{"op": "replace", "path": "/spec/replicas", "value": 2}]'
- target:
    kind: Deployment
    name: dispute-service
  patch: '[{"op": "replace", "path": "/spec/replicas", "value": 2}]'
- target:
    kind: Deployment
    name: fx-service
  patch: '[{"op": "replace", "path": "/spec/replicas", "value": 2}]'
- target:
    kind: Deployment
    name: gateway-service
  patch: '[{"op": "replace", "path": "/spec/replicas", "value": 2}]'
- target:
    kind: Deployment
    name: integration-service
  patch: '[{"op": "replace", "path": "/spec/replicas", "value": 2}]'
- target:
    kind: Deployment
    name: investment-service
  patch: '[{"op": "replace", "path": "/spec/replicas", "value": 2}]'
- target:
    kind: Deployment
    name: kyc-service
  patch: '[{"op": "replace", "path": "/spec/replicas", "value": 2}]'
- target:
    kind: Deployment
    name: lending-service
  patch: '[{"op": "replace", "path": "/spec/replicas", "value": 2}]'
- target:
    kind: Deployment
    name: notification-service
  patch: '[{"op": "replace", "path": "/spec/replicas", "value": 2}]'
- target:
    kind: Deployment
    name: partner-service
  patch: '[{"op": "replace", "path": "/spec/replicas", "value": 2}]'
- target:
    kind: Deployment
    name: product-catalog-service
  patch: '[{"op": "replace", "path": "/spec/replicas", "value": 2}]'
- target:
    kind: Deployment
    name: promotion-service
  patch: '[{"op": "replace", "path": "/spec/replicas", "value": 2}]'
- target:
    kind: Deployment
    name: statement-service
  patch: '[{"op": "replace", "path": "/spec/replicas", "value": 2}]'
- target:
    kind: Deployment
    name: support-service
  patch: '[{"op": "replace", "path": "/spec/replicas", "value": 2}]'
- target:
    kind: Deployment
    name: transaction-service
  patch: '[{"op": "replace", "path": "/spec/replicas", "value": 2}]'
- target:
    kind: Deployment
    name: wallet-service
  patch: '[{"op": "replace", "path": "/spec/replicas", "value": 2}]'
- target:
    kind: Deployment
    name: web-app
  patch: '[{"op": "replace", "path": "/spec/replicas", "value": 2}]'
labels:
- pairs:
    environment: preprod
  includeSelectors: false
