apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: payu
resources:
  - ../../../base/auth-service
images:
  - name: image-registry.openshift-image-registry.svc:5000/payu-dev/auth-service
    newName: image-registry.openshift-image-registry.svc:5000/payu/auth-service
    newTag: "1.18.55"
patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: auth-service
      spec:
        template:
          spec:
            containers:
              - name: app
                env:
                  - name: OIDC_ISSUER
                    value: "https://sso-prod.apps.fajjjar.my.id/realms/payu"
                  - name: OIDC_JWK_SET_URI
                    value: "https://sso-prod.apps.fajjjar.my.id/realms/payu/protocol/openid-connect/certs"
