apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: payu
resources:
  - ../../../base/auth-service
images:
  - name: image-registry.openshift-image-registry.svc:5000/payu-dev/auth-service
    newName: image-registry.openshift-image-registry.svc:5000/payu/auth-service
    newTag: "1.18.8"
